import { defineConfig } from "vite-plus";
import { devtools } from "@tanstack/devtools-vite";

import { tanstackStart } from "@tanstack/react-start/plugin/vite";

import viteReact, { reactCompilerPreset } from "@vitejs/plugin-react";
import babel from "@rolldown/plugin-babel";
import tailwindcss from "@tailwindcss/vite";
import { nitro } from "nitro/vite";

// The type-aware lint path (tsgolint over the TypeScript Go toolchain) needs
// ~4GB of memory, which the dev machine cannot spare. Gate it behind CI so
// GitHub Actions runs the full type-aware lint while local `vp check` stays
// light (fmt + non-type-aware lint). Override locally with `CI=true vp check`.
const isCI = !!process.env.CI;

const agentToolingIgnores = [
  ".agent/**",
  ".agents/**",
  ".claude/**",
  ".codex/**",
  ".continue/**",
  ".cursor/**",
  ".gemini/**",
  ".opencode/**",
  ".pi/**",
  ".roo/**",
  ".windsurf/**",
  ".impeccable/**",
  ".content-collections/**",
  "tools/**",
  // Generated by TanStack Router on build; its own header says to exclude it
  // from the linter and formatter so it isn't checked or reformatted.
  "src/routeTree.gen.ts",
];

const config = defineConfig({
  staged: {
    "*": "vp check --fix",
  },
  fmt: {
    ignorePatterns: agentToolingIgnores,
  },
  lint: {
    ignorePatterns: agentToolingIgnores,
    options: { typeAware: isCI, typeCheck: isCI },
    jsPlugins: [
      {
        name: "anti-slop",
        specifier: "./tools/oxlint/anti-slop/index.ts",
      },
    ],
    rules: {
      "anti-slop/no-chained-type-assertions": "error",
      "anti-slop/no-conditional-empty-object-spread": "error",
      "anti-slop/no-known-value-widening": "error",
      "anti-slop/no-module-mocking": "error",
      "anti-slop/no-object-parameters": "error",
      "anti-slop/no-reflect-apply": "error",
      "anti-slop/no-reflect-get": "error",
      "anti-slop/no-runtime-typeof": "error",
      "anti-slop/no-shape-in-symbol-names": "error",
      "anti-slop/no-unknown-parameters": "error",
      "anti-slop/no-unknown-returns": "error",
      "anti-slop/no-unknown-type-aliases": "error",
      "anti-slop/no-unsafe-dictionary-type": "error",
      "anti-slop/no-widen-then-assert": "error",
      "anti-slop/require-safety-comment-for-type-assertion": "error",
    },
  },
  resolve: {
    tsconfigPaths: true,
    dedupe: ["react", "react-dom"],
  },
  test: {
    // Integration flow tests share ONE database. `setupFlowHarness`
    // (src/lib/server/integration-test-harness.ts) TRUNCATEs the root tables
    // (`users`, `branches`, `ingredients`, …) in `beforeEach` so each test
    // starts clean — which is only safe while one test file runs at a time.
    // Under Vitest's default file-level parallelism a second file's
    // beforeEach wipes the first file's rows mid-test.
    //
    // That race is not theoretical: it surfaced as three stock-opname tests
    // failing in the full suite while passing in isolation, purely because
    // adding tests to that file widened its overlap window. Serialising is the
    // fix; giving every file its own database is the alternative, and is worth
    // doing if the suite's wall-clock ever becomes a problem.
    //
    // Set here rather than as a `--no-file-parallelism` flag on the package.json
    // script, because CI runs `vp test run` directly and would miss the flag.
    fileParallelism: false,
  },
  plugins: [
    devtools(),
    nitro({ rollupConfig: { external: [/^@sentry\//] } }),
    tailwindcss(),
    tanstackStart(),
    viteReact(),
    babel({ presets: [reactCompilerPreset()] }),
  ],
});

export default config;
