import { defineConfig } from "vite-plus";
import { devtools } from "@tanstack/devtools-vite";

import { tanstackStart } from "@tanstack/react-start/plugin/vite";

import viteReact, { reactCompilerPreset } from "@vitejs/plugin-react";
import babel from "@rolldown/plugin-babel";
import tailwindcss from "@tailwindcss/vite";
import { nitro } from "nitro/vite";

// The type-aware lint path (tsgolint over the TypeScript Go toolchain) needs
// ~4GB of memory, which the dev machine cannot spare. Gate it behind CI so
// GitHub Actions runs the full type-aware lint while local `vp check` stays
// light (fmt + non-type-aware lint). Override locally with `CI=true vp check`.
const isCI = !!process.env.CI;

const agentToolingIgnores = [
  ".agent/**",
  ".agents/**",
  ".claude/**",
  ".codex/**",
  ".continue/**",
  ".cursor/**",
  ".gemini/**",
  ".opencode/**",
  ".pi/**",
  ".roo/**",
  ".windsurf/**",
  ".impeccable/**",
  ".content-collections/**",
  "tools/**",
  // Generated by TanStack Router on build; its own header says to exclude it
  // from the linter and formatter so it isn't checked or reformatted.
  "src/routeTree.gen.ts",
];

const config = defineConfig({
  staged: {
    "*": "vp check --fix",
  },
  fmt: {
    ignorePatterns: agentToolingIgnores,
  },
  lint: {
    ignorePatterns: agentToolingIgnores,
    options: { typeAware: isCI, typeCheck: isCI },
  },
  resolve: { tsconfigPaths: true },
  plugins: [
    devtools(),
    nitro({ rollupConfig: { external: [/^@sentry\//] } }),
    tailwindcss(),
    tanstackStart(),
    viteReact(),
    babel({ presets: [reactCompilerPreset()] }),
  ],
});

export default config;
