-- Gives stock_ledger a monotonic insertion order.
--
-- `created_at` is `defaultNow()`, a *transaction* timestamp, so every row written
-- in one transaction shares it: a POS order, a Mutasi receive, an Edit Order's
-- restore+deduct pair, a whole Sesuaikan Stok batch. `id` is `defaultRandom()`, so
-- the existing tiebreaker on those ties is a random uuid — the order rows of one
-- batch appear in, and the order their balances must be summed in, is arbitrary.
--
-- The Kartu Stok Saldo is a running movement total, so that arbitrariness is
-- visible: within a batch the column can read backwards. `seq` is the order the
-- writer actually applied the movements in, which is what the total needs.
--
-- BY DEFAULT, not ALWAYS: the backfill migrations and repair scripts that INSERT
-- into stock_ledger with an explicit column list must keep working, and they take
-- a sequence value rather than an explicit one.
ALTER TABLE "stock_ledger"
  ADD COLUMN IF NOT EXISTS "seq" bigint GENERATED BY DEFAULT AS IDENTITY;
--> statement-breakpoint
-- Serves the Saldo history read, which filters a page's series and walks them in
-- insertion order. The pre-existing single-column indexes let Postgres pick one and
-- filter the rest, reading thousands of rows to return fifteen.
CREATE INDEX IF NOT EXISTS "ledger_branch_ingredient_seq_idx"
  ON "stock_ledger" ("branch_id", "ingredient_id", "seq");