// ──────────────────────────────────────────
// Prototype data adapted for the current schema

function nDaysAgo(n: number): Date {
  const d = new Date();
  d.setDate(d.getDate() - n);
  return d;
}
// ──────────────────────────────────────────

export const BRANCHES = [
  {
    protoId: "br-central",
    code: "CENTRAL",
    name: "Central Warehouse",
    location: "Pusat",
    type: "Central" as const,
    active: true,
    isOnline: true,
  },
  {
    protoId: "br-sub-01",
    code: "SBY-01",
    name: "Omoiyari Surabaya Pusat",
    location: "Tegalsari, Surabaya",
    type: "Outlet" as const,
    active: true,
    isOnline: true,
  },
  {
    protoId: "br-sub-02",
    code: "SBY-02",
    name: "Omoiyari Surabaya Barat",
    location: "Sambikerep, Surabaya",
    type: "Outlet" as const,
    active: true,
    isOnline: false,
  },
  {
    protoId: "br-sub-03",
    code: "SBY-03",
    name: "Omoiyari Surabaya Timur",
    location: "Mulyorejo, Surabaya",
    type: "Outlet" as const,
    active: true,
    isOnline: true,
  },
  {
    protoId: "br-sub-04",
    code: "SBY-04",
    name: "Omoiyari Sidoarjo",
    location: "Waru, Sidoarjo",
    type: "Outlet" as const,
    active: true,
    isOnline: true,
  },
  {
    protoId: "br-mlg-01",
    code: "MLG-01",
    name: "Omoiyari Malang",
    location: "Lowokwaru, Malang",
    type: "Outlet" as const,
    active: true,
    isOnline: true,
  },
  {
    protoId: "br-grs-01",
    code: "GRS-01",
    name: "Omoiyari Gresik",
    location: "Kebomas, Gresik",
    type: "Outlet" as const,
    active: true,
    isOnline: true,
  },
  {
    protoId: "br-jkt-01",
    code: "JKT-01",
    name: "Omoiyari Jakarta Selatan",
    location: "Tebet, Jakarta",
    type: "Outlet" as const,
    active: true,
    isOnline: true,
  },
  {
    protoId: "br-jkt-02",
    code: "JKT-02",
    name: "Omoiyari Jakarta Barat",
    location: "Puri, Jakarta",
    type: "Outlet" as const,
    active: true,
    isOnline: true,
  },
  {
    protoId: "br-bdg-01",
    code: "BDG-01",
    name: "Omoiyari Bandung",
    location: "Dago, Bandung",
    type: "Outlet" as const,
    active: true,
    isOnline: true,
  },
];

export const BRANDS = [{ code: "BRAND-1", name: "Omoiyari" }];

export const SUPPLIERS = [
  { code: "SUP-001", name: "PT Beras Makmur", contactPerson: "Budi", phone: "08123456789" },
  { code: "SUP-002", name: "CV Ayam Segar", contactPerson: "Siti", phone: "08123456780" },
  { code: "SUP-003", name: "Importir Sapi Jaya", contactPerson: "Joko", phone: "08123456781" },
  { code: "SUP-004", name: "PT Saus Nusantara", contactPerson: "Rina", phone: "08123456782" },
];

export const USERS_TO_CREATE = [
  {
    email: "superadmin@omoiyari.net",
    password: "password123",
    name: "Super Admin",
    role: "super_admin" as const,
  },
  {
    email: "pusat@omoiyari.net",
    password: "password123",
    name: "Admin Pusat",
    role: "admin_pusat" as const,
  },
  {
    email: "manager.east@omoiyari.net",
    password: "password123",
    name: "Area Manager East",
    role: "area_manager" as const,
  },
  {
    email: "hans@omoiyari.net",
    password: "password123",
    name: "Hans",
    role: "branch_admin" as const,
    branchCode: "SBY-01",
  },
  {
    email: "ck@omoiyari.net",
    password: "password123",
    name: "Central Kitchen",
    role: "central_kitchen" as const,
    branchCode: "CENTRAL",
  },
];

export const AREA_MANAGER_BRANCHES = ["SBY-01", "SBY-02", "SBY-03", "SBY-04"];

export const INGREDIENTS = [
  {
    protoId: "ing-01",
    code: "ING-001",
    name: "Beras Premium",
    category: "Dry" as const,
    skuType: "RM" as const,
    purchaseUnit: "Karung 25kg",
    stockUnit: "Gram",
    conversionFactor: 25000,
    averageCost: 350000,
    rop: 50000,
    moq: 2,
    countable: true,
  },
  {
    protoId: "ing-02",
    code: "ING-002",
    name: "Daging Ayam Fillet",
    category: "Fresh" as const,
    skuType: "RM" as const,
    purchaseUnit: "Kg",
    stockUnit: "Gram",
    conversionFactor: 1000,
    averageCost: 45000,
    rop: 5000,
    moq: 5,
    countable: true,
  },
  {
    protoId: "ing-03",
    code: "ING-003",
    name: "Daging Sapi Slice",
    category: "Fresh" as const,
    skuType: "RM" as const,
    purchaseUnit: "Kg",
    stockUnit: "Gram",
    conversionFactor: 1000,
    averageCost: 115000,
    rop: 3000,
    moq: 2,
    countable: true,
  },
  {
    protoId: "ing-04",
    code: "ING-004",
    name: "Saus Teriyaki",
    category: "Dry" as const,
    skuType: "RM" as const,
    purchaseUnit: "Jerigen 5L",
    stockUnit: "Ml",
    conversionFactor: 5000,
    averageCost: 120000,
    rop: 10000,
    moq: 1,
    countable: true,
  },
  {
    protoId: "ing-05",
    code: "ING-005",
    name: "Saus Yakiniku",
    category: "Dry" as const,
    skuType: "RM" as const,
    purchaseUnit: "Jerigen 5L",
    stockUnit: "Ml",
    conversionFactor: 5000,
    averageCost: 135000,
    rop: 10000,
    moq: 1,
    countable: true,
  },
  {
    protoId: "ing-06",
    code: "ING-006",
    name: "Curry Roux",
    category: "Dry" as const,
    skuType: "RM" as const,
    purchaseUnit: "Box 1kg",
    stockUnit: "Gram",
    conversionFactor: 1000,
    averageCost: 180000,
    rop: 2000,
    moq: 1,
    countable: true,
  },
  {
    protoId: "ing-07",
    code: "ING-007",
    name: "Telur Ayam",
    category: "Fresh" as const,
    skuType: "RM" as const,
    purchaseUnit: "Tray 30pcs",
    stockUnit: "Pcs",
    conversionFactor: 30,
    averageCost: 60000,
    rop: 90,
    moq: 3,
    countable: true,
  },
  {
    protoId: "ing-08",
    code: "ING-008",
    name: "Kentang",
    category: "Fresh" as const,
    skuType: "RM" as const,
    purchaseUnit: "Kg",
    stockUnit: "Gram",
    conversionFactor: 1000,
    averageCost: 180000,
    rop: 5000,
    moq: 10,
    countable: true,
  },
  {
    protoId: "ing-09",
    code: "ING-009",
    name: "Wortel",
    category: "Fresh" as const,
    skuType: "RM" as const,
    purchaseUnit: "Kg",
    stockUnit: "Gram",
    conversionFactor: 1000,
    averageCost: 15000,
    rop: 3000,
    moq: 5,
    countable: true,
  },
  {
    protoId: "ing-10",
    code: "ING-010",
    name: "Bawang Bombay",
    category: "Fresh" as const,
    skuType: "RM" as const,
    purchaseUnit: "Kg",
    stockUnit: "Gram",
    conversionFactor: 1000,
    averageCost: 25000,
    rop: 3000,
    moq: 5,
    countable: true,
  },
  {
    protoId: "ing-11",
    code: "ING-011",
    name: "Tepung Panko",
    category: "Dry" as const,
    skuType: "RM" as const,
    purchaseUnit: "Kg",
    stockUnit: "Gram",
    conversionFactor: 1000,
    averageCost: 28000,
    rop: 5000,
    moq: 10,
    countable: true,
  },
  {
    protoId: "ing-12",
    code: "ING-012",
    name: "Minyak Goreng",
    category: "Dry" as const,
    skuType: "RM" as const,
    purchaseUnit: "Pouch 2L",
    stockUnit: "Ml",
    conversionFactor: 2000,
    averageCost: 35000,
    rop: 10000,
    moq: 6,
    countable: true,
  },
  {
    protoId: "ing-13",
    code: "ING-013",
    name: "Kulit Gyoza",
    category: "Fresh" as const,
    skuType: "RM" as const,
    purchaseUnit: "Pack 50pcs",
    stockUnit: "Pcs",
    conversionFactor: 50,
    averageCost: 20000,
    rop: 200,
    moq: 10,
    countable: true,
  },
  {
    protoId: "ing-14",
    code: "ING-014",
    name: "Daging Ayam Cincang",
    category: "Fresh" as const,
    skuType: "RM" as const,
    purchaseUnit: "Kg",
    stockUnit: "Gram",
    conversionFactor: 1000,
    averageCost: 42000,
    rop: 5000,
    moq: 5,
    countable: true,
  },
  {
    protoId: "ing-15",
    code: "ING-015",
    name: "Miso Paste",
    category: "Dry" as const,
    skuType: "RM" as const,
    purchaseUnit: "Tub 1kg",
    stockUnit: "Gram",
    conversionFactor: 1000,
    averageCost: 85000,
    rop: 2000,
    moq: 1,
    countable: true,
  },
  {
    protoId: "ing-19",
    code: "ING-016",
    name: "Tepung Karaage",
    category: "Dry" as const,
    skuType: "RM" as const,
    purchaseUnit: "Kg",
    stockUnit: "Gram",
    conversionFactor: 1000,
    averageCost: 45000,
    rop: 5000,
    moq: 5,
    countable: true,
  },
  {
    protoId: "ing-21",
    code: "ING-017",
    name: "Nori (Rumput Laut)",
    category: "Dry" as const,
    skuType: "RM" as const,
    purchaseUnit: "Pack 50 sheets",
    stockUnit: "Pcs",
    conversionFactor: 50,
    averageCost: 65000,
    rop: 100,
    moq: 2,
    countable: true,
  },
  {
    protoId: "ing-22",
    code: "ING-018",
    name: "Daging Ayam Utuh (Mentah)",
    category: "Fresh" as const,
    skuType: "RM" as const,
    purchaseUnit: "Ekor",
    stockUnit: "Gram",
    conversionFactor: 1200,
    averageCost: 40000,
    rop: 20000,
    moq: 10,
    countable: true,
  },
  {
    protoId: "ing-23",
    code: "ING-019",
    name: "Minyak Wijen",
    category: "Dry" as const,
    skuType: "RM" as const,
    purchaseUnit: "Botol 1L",
    stockUnit: "Ml",
    conversionFactor: 1000,
    averageCost: 55000,
    rop: 2000,
    moq: 2,
    countable: true,
  },
  {
    protoId: "ing-24",
    code: "ING-020",
    name: "Kecap Asin",
    category: "Dry" as const,
    skuType: "RM" as const,
    purchaseUnit: "Botol 2L",
    stockUnit: "Ml",
    conversionFactor: 2000,
    averageCost: 45000,
    rop: 4000,
    moq: 2,
    countable: true,
  },
  {
    protoId: "ing-25",
    code: "ING-021",
    name: "Garam",
    category: "Dry" as const,
    skuType: "RM" as const,
    purchaseUnit: "Pack 1Kg",
    stockUnit: "Gram",
    conversionFactor: 1000,
    averageCost: 15000,
    rop: 5000,
    moq: 5,
    countable: true,
  },
  {
    protoId: "ing-26",
    code: "ING-022",
    name: "Gula",
    category: "Dry" as const,
    skuType: "RM" as const,
    purchaseUnit: "Pack 1Kg",
    stockUnit: "Gram",
    conversionFactor: 1000,
    averageCost: 18000,
    rop: 5000,
    moq: 5,
    countable: true,
  },
  {
    protoId: "ing-27",
    code: "ING-023",
    name: "Bawang Putih",
    category: "Fresh" as const,
    skuType: "RM" as const,
    purchaseUnit: "Kg",
    stockUnit: "Gram",
    conversionFactor: 1000,
    averageCost: 40000,
    rop: 3000,
    moq: 3,
    countable: true,
  },
  // Packaging (FG)
  {
    protoId: "ing-16",
    code: "ING-024",
    name: "Paper Bowl 650ml",
    category: "Packaging" as const,
    skuType: "FG" as const,
    purchaseUnit: "Pack 50pcs",
    stockUnit: "Pcs",
    conversionFactor: 50,
    averageCost: 1500,
    rop: 250,
    moq: 20,
    countable: true,
  },
  {
    protoId: "ing-17",
    code: "ING-025",
    name: "Sumpit & Sendok Set",
    category: "Packaging" as const,
    skuType: "FG" as const,
    purchaseUnit: "Pack 100pcs",
    stockUnit: "Pcs",
    conversionFactor: 100,
    averageCost: 450,
    rop: 500,
    moq: 10,
    countable: true,
  },
  {
    protoId: "ing-18",
    code: "ING-026",
    name: "Kantong Plastik",
    category: "Packaging" as const,
    skuType: "FG" as const,
    purchaseUnit: "Pack 50pcs",
    stockUnit: "Pcs",
    conversionFactor: 50,
    averageCost: 300,
    rop: 250,
    moq: 10,
    countable: true,
  },
  {
    protoId: "ing-20",
    code: "ING-027",
    name: "Tusuk Sate",
    category: "Packaging" as const,
    skuType: "FG" as const,
    purchaseUnit: "Pack 100pcs",
    stockUnit: "Pcs",
    conversionFactor: 100,
    averageCost: 100,
    rop: 500,
    moq: 5,
    countable: true,
  },
  // Semi-Finished Goods (SFG)
  {
    protoId: "ing-sfg-01",
    code: "ING-028",
    name: "Nasi Putih Matang",
    category: "Fresh" as const,
    skuType: "SFG" as const,
    purchaseUnit: "Gram",
    stockUnit: "Gram",
    conversionFactor: 1,
    averageCost: 15,
    rop: 5000,
    moq: 1,
    countable: true,
  },
  {
    protoId: "ing-sfg-02",
    code: "ING-029",
    name: "Ayam Teriyaki Matang",
    category: "Fresh" as const,
    skuType: "SFG" as const,
    purchaseUnit: "Gram",
    stockUnit: "Gram",
    conversionFactor: 1,
    averageCost: 65,
    rop: 2000,
    moq: 1,
    countable: true,
  },
  {
    protoId: "ing-sfg-03",
    code: "ING-030",
    name: "Beef Yakiniku Matang",
    category: "Fresh" as const,
    skuType: "SFG" as const,
    purchaseUnit: "Gram",
    stockUnit: "Gram",
    conversionFactor: 1,
    averageCost: 145,
    rop: 2000,
    moq: 1,
    countable: true,
  },
  {
    protoId: "ing-sfg-04",
    code: "ING-031",
    name: "Chicken Katsu Matang",
    category: "Fresh" as const,
    skuType: "SFG" as const,
    purchaseUnit: "Pcs",
    stockUnit: "Pcs",
    conversionFactor: 1,
    averageCost: 8000,
    rop: 50,
    moq: 1,
    countable: true,
  },
  {
    protoId: "ing-sfg-05",
    code: "ING-032",
    name: "Saus Curry Matang",
    category: "Fresh" as const,
    skuType: "SFG" as const,
    purchaseUnit: "Ml",
    stockUnit: "Ml",
    conversionFactor: 1,
    averageCost: 45,
    rop: 2000,
    moq: 1,
    countable: true,
  },
  {
    protoId: "ing-sfg-06",
    code: "ING-033",
    name: "Gyoza Goreng",
    category: "Fresh" as const,
    skuType: "SFG" as const,
    purchaseUnit: "Pcs",
    stockUnit: "Pcs",
    conversionFactor: 1,
    averageCost: 4000,
    rop: 100,
    moq: 1,
    countable: true,
  },
  {
    protoId: "ing-sfg-07",
    code: "ING-034",
    name: "Miso Soup Matang",
    category: "Fresh" as const,
    skuType: "SFG" as const,
    purchaseUnit: "Ml",
    stockUnit: "Ml",
    conversionFactor: 1,
    averageCost: 25,
    rop: 2000,
    moq: 1,
    countable: true,
  },
  {
    protoId: "ing-sfg-08",
    code: "ING-035",
    name: "Oyakodon Topping Matang",
    category: "Fresh" as const,
    skuType: "SFG" as const,
    purchaseUnit: "Porsi",
    stockUnit: "Porsi",
    conversionFactor: 1,
    averageCost: 12000,
    rop: 30,
    moq: 1,
    countable: true,
  },
  {
    protoId: "ing-sfg-09",
    code: "ING-036",
    name: "Chicken Karaage Matang",
    category: "Fresh" as const,
    skuType: "SFG" as const,
    purchaseUnit: "Gram",
    stockUnit: "Gram",
    conversionFactor: 1,
    averageCost: 55,
    rop: 2000,
    moq: 1,
    countable: true,
  },
  {
    protoId: "ing-sfg-10",
    code: "ING-037",
    name: "Tamagoyaki Matang",
    category: "Fresh" as const,
    skuType: "SFG" as const,
    purchaseUnit: "Pcs",
    stockUnit: "Pcs",
    conversionFactor: 1,
    averageCost: 3000,
    rop: 50,
    moq: 1,
    countable: true,
  },
  {
    protoId: "ing-sfg-11",
    code: "ING-038",
    name: "Yakitori Matang",
    category: "Fresh" as const,
    skuType: "SFG" as const,
    purchaseUnit: "Pcs",
    stockUnit: "Pcs",
    conversionFactor: 1,
    averageCost: 5000,
    rop: 50,
    moq: 1,
    countable: true,
  },
  {
    protoId: "ing-sfg-12",
    code: "ING-039",
    name: "Telur Mata Sapi Matang",
    category: "Fresh" as const,
    skuType: "SFG" as const,
    purchaseUnit: "Pcs",
    stockUnit: "Pcs",
    conversionFactor: 1,
    averageCost: 3000,
    rop: 50,
    moq: 1,
    countable: true,
  },
  {
    protoId: "ing-sfg-13",
    code: "ING-040",
    name: "Daging Sapi Slice Matang",
    category: "Fresh" as const,
    skuType: "SFG" as const,
    purchaseUnit: "Gram",
    stockUnit: "Gram",
    conversionFactor: 1,
    averageCost: 155,
    rop: 2000,
    moq: 1,
    countable: true,
  },
  {
    protoId: "ing-sfg-14",
    code: "ING-041",
    name: "Potongan Ayam Karaage Mentah",
    category: "Fresh" as const,
    skuType: "SFG" as const,
    purchaseUnit: "Gram",
    stockUnit: "Gram",
    conversionFactor: 1,
    averageCost: 50,
    rop: 2000,
    moq: 1,
    countable: true,
  },
];

export const MODIFIER_GROUPS_DATA = [
  {
    protoId: "mg-01",
    code: "MG-001",
    name: "Level Pedas",
    minSelection: 1,
    maxSelection: 1,
    modifiers: [
      {
        protoId: "mod-01",
        code: "MOD-001",
        name: "Original (Tidak Pedas)",
        price: 0,
        isExclusion: false,
      },
      {
        protoId: "mod-02",
        code: "MOD-002",
        name: "Level 1 (Sedang)",
        price: 0,
        isExclusion: false,
      },
      {
        protoId: "mod-03",
        code: "MOD-003",
        name: "Level 2 (Pedas)",
        price: 2000,
        isExclusion: false,
      },
      {
        protoId: "mod-04",
        code: "MOD-004",
        name: "Level 3 (Sangat Pedas)",
        price: 5000,
        isExclusion: false,
      },
    ],
  },
  {
    protoId: "mg-02",
    code: "MG-002",
    name: "Extra Topping",
    minSelection: 0,
    maxSelection: 5,
    modifiers: [
      {
        protoId: "mod-05",
        code: "MOD-005",
        name: "Extra Telur Mata Sapi",
        price: 5000,
        isExclusion: false,
        ingredients: [{ ingredientProtoId: "ing-sfg-12", quantity: 1 }],
      },
      {
        protoId: "mod-06",
        code: "MOD-006",
        name: "Extra Daging Ayam",
        price: 10000,
        isExclusion: false,
        ingredients: [{ ingredientProtoId: "ing-sfg-02", quantity: 50 }],
      },
      {
        protoId: "mod-07",
        code: "MOD-007",
        name: "Extra Keju Slice",
        price: 4000,
        isExclusion: false,
      },
    ],
  },
  {
    protoId: "mg-03",
    code: "MG-003",
    name: "Pilihan (Exclusion)",
    minSelection: 0,
    maxSelection: 3,
    modifiers: [
      {
        protoId: "mod-08",
        code: "MOD-008",
        name: "Tanpa Bawang Bombay",
        price: 0,
        isExclusion: true,
      },
      { protoId: "mod-09", code: "MOD-009", name: "Tanpa Wortel", price: 0, isExclusion: true },
    ],
  },
];

export const RECIPES_DATA = [
  {
    protoId: "rec-01",
    code: "REC-001",
    name: "Chicken Teriyaki Bowl",
    category: "makanan" as const,
    isSubRecipe: false,
    basePrice: 35000,
    isBOGO: false,
    brandProtoIds: ["brand-1"],
    ingredients: [
      { ingredientProtoId: "ing-sfg-01", quantity: 200 },
      { ingredientProtoId: "ing-sfg-02", quantity: 150 },
      { ingredientProtoId: "ing-16", quantity: 1 },
      { ingredientProtoId: "ing-17", quantity: 1 },
    ],
    modifierGroupProtoIds: ["mg-01", "mg-02", "mg-03"],
  },
  {
    protoId: "rec-02",
    code: "REC-002",
    name: "Beef Yakiniku Bowl",
    category: "makanan" as const,
    isSubRecipe: false,
    basePrice: 48000,
    isBOGO: false,
    brandProtoIds: ["brand-1"],
    ingredients: [
      { ingredientProtoId: "ing-sfg-01", quantity: 200 },
      { ingredientProtoId: "ing-sfg-03", quantity: 150 },
      { ingredientProtoId: "ing-16", quantity: 1 },
      { ingredientProtoId: "ing-17", quantity: 1 },
    ],
    modifierGroupProtoIds: ["mg-01", "mg-02", "mg-03"],
  },
  {
    protoId: "rec-03",
    code: "REC-003",
    name: "Chicken Katsu Curry",
    category: "makanan" as const,
    isSubRecipe: false,
    basePrice: 42000,
    isBOGO: false,
    brandProtoIds: ["brand-1"],
    ingredients: [
      { ingredientProtoId: "ing-sfg-01", quantity: 200 },
      { ingredientProtoId: "ing-sfg-04", quantity: 1 },
      { ingredientProtoId: "ing-sfg-05", quantity: 100 },
      { ingredientProtoId: "ing-16", quantity: 1 },
      { ingredientProtoId: "ing-17", quantity: 1 },
    ],
  },
  {
    protoId: "rec-bundle-01",
    code: "REC-004",
    name: "Family Pack (2 Chicken + 1 Beef)",
    category: "makanan" as const,
    isSubRecipe: false,
    basePrice: 100000,
    isBOGO: false,
    brandProtoIds: ["brand-1"],
    ingredients: [{ ingredientProtoId: "ing-18", quantity: 1 }],
    childRecipes: [
      { recipeProtoId: "rec-01", quantity: 2 },
      { recipeProtoId: "rec-02", quantity: 1 },
    ],
  },
  {
    protoId: "rec-bogo-01",
    code: "REC-005",
    name: "PROMO: BOGO Chicken Bowl",
    category: "makanan" as const,
    isSubRecipe: false,
    basePrice: 45000,
    isBOGO: true,
    brandProtoIds: ["brand-1"],
    ingredients: [],
    childRecipes: [{ recipeProtoId: "rec-01", quantity: 2 }],
  },
  {
    protoId: "rec-04",
    code: "REC-006",
    name: "Gyoza (5pcs)",
    category: "makanan" as const,
    isSubRecipe: false,
    basePrice: 25000,
    isBOGO: false,
    brandProtoIds: ["brand-1"],
    ingredients: [
      { ingredientProtoId: "ing-sfg-06", quantity: 5 },
      { ingredientProtoId: "ing-18", quantity: 1 },
    ],
  },
  {
    protoId: "rec-05",
    code: "REC-007",
    name: "Miso Soup",
    category: "snack" as const,
    isSubRecipe: false,
    basePrice: 12000,
    isBOGO: false,
    brandProtoIds: ["brand-1"],
    ingredients: [
      { ingredientProtoId: "ing-sfg-07", quantity: 200 },
      { ingredientProtoId: "ing-16", quantity: 1 },
    ],
  },
  {
    protoId: "rec-06",
    code: "REC-008",
    name: "Oyakodon",
    category: "makanan" as const,
    isSubRecipe: false,
    basePrice: 38000,
    isBOGO: false,
    brandProtoIds: ["brand-1"],
    ingredients: [
      { ingredientProtoId: "ing-sfg-01", quantity: 200 },
      { ingredientProtoId: "ing-sfg-08", quantity: 1 },
      { ingredientProtoId: "ing-16", quantity: 1 },
      { ingredientProtoId: "ing-17", quantity: 1 },
    ],
  },
  {
    protoId: "rec-07",
    code: "REC-009",
    name: "Chicken Karaage Bowl",
    category: "makanan" as const,
    isSubRecipe: false,
    basePrice: 36000,
    isBOGO: false,
    brandProtoIds: ["brand-1"],
    ingredients: [
      { ingredientProtoId: "ing-sfg-01", quantity: 200 },
      { ingredientProtoId: "ing-sfg-09", quantity: 150 },
      { ingredientProtoId: "ing-16", quantity: 1 },
      { ingredientProtoId: "ing-17", quantity: 1 },
    ],
  },
  {
    protoId: "rec-08",
    code: "REC-010",
    name: "Beef Curry Bowl",
    category: "makanan" as const,
    isSubRecipe: false,
    basePrice: 52000,
    isBOGO: false,
    brandProtoIds: ["brand-1"],
    ingredients: [
      { ingredientProtoId: "ing-sfg-01", quantity: 200 },
      { ingredientProtoId: "ing-sfg-03", quantity: 100 },
      { ingredientProtoId: "ing-sfg-05", quantity: 100 },
      { ingredientProtoId: "ing-16", quantity: 1 },
      { ingredientProtoId: "ing-17", quantity: 1 },
    ],
  },
  {
    protoId: "rec-09",
    code: "REC-011",
    name: "Tamagoyaki (4pcs)",
    category: "snack" as const,
    isSubRecipe: false,
    basePrice: 15000,
    isBOGO: false,
    brandProtoIds: ["brand-1"],
    ingredients: [
      { ingredientProtoId: "ing-sfg-10", quantity: 4 },
      { ingredientProtoId: "ing-18", quantity: 1 },
    ],
  },
  {
    protoId: "rec-10",
    code: "REC-012",
    name: "Yakitori Set (3pcs)",
    category: "makanan" as const,
    isSubRecipe: false,
    basePrice: 22000,
    isBOGO: false,
    brandProtoIds: ["brand-1"],
    ingredients: [
      { ingredientProtoId: "ing-sfg-11", quantity: 3 },
      { ingredientProtoId: "ing-20", quantity: 3 },
      { ingredientProtoId: "ing-18", quantity: 1 },
    ],
  },
  {
    protoId: "rec-11",
    code: "REC-013",
    name: "Salmon Teriyaki Bowl",
    category: "makanan" as const,
    isSubRecipe: false,
    basePrice: 65000,
    isBOGO: false,
    brandProtoIds: ["brand-1"],
    ingredients: [
      { ingredientProtoId: "ing-sfg-01", quantity: 200 },
      { ingredientProtoId: "ing-sfg-02", quantity: 100 },
      { ingredientProtoId: "ing-16", quantity: 1 },
      { ingredientProtoId: "ing-17", quantity: 1 },
    ],
  },
  {
    protoId: "rec-12",
    code: "REC-014",
    name: "Ebi Furai (3pcs)",
    category: "snack" as const,
    isSubRecipe: false,
    basePrice: 32000,
    isBOGO: false,
    brandProtoIds: ["brand-1"],
    ingredients: [
      { ingredientProtoId: "ing-sfg-04", quantity: 3 },
      { ingredientProtoId: "ing-18", quantity: 1 },
    ],
  },
  {
    protoId: "rec-13",
    code: "REC-015",
    name: "Unagi Bowl",
    category: "snack" as const,
    isSubRecipe: false,
    basePrice: 85000,
    isBOGO: false,
    brandProtoIds: ["brand-1"],
    ingredients: [
      { ingredientProtoId: "ing-sfg-01", quantity: 200 },
      { ingredientProtoId: "ing-16", quantity: 1 },
      { ingredientProtoId: "ing-17", quantity: 1 },
    ],
  },
];

export const ORDERS_DATA = (() => {
  const branches = [
    "SBY-01",
    "SBY-02",
    "SBY-03",
    "SBY-04",
    "SBY-01",
    "SBY-04",
    "MLG-01",
    "GRS-01",
    "JKT-01",
    "JKT-02",
    "BDG-01",
    "SBY-01",
    "SBY-02",
    "SBY-03",
    "SBY-04",
    "SBY-01",
    "SBY-02",
    "SBY-03",
    "SBY-04",
    "MLG-01",
    "GRS-01",
    "JKT-01",
    "JKT-02",
    "BDG-01",
    "SBY-01",
    "SBY-02",
    "SBY-03",
    "SBY-04",
    "MLG-01",
    "GRS-01",
    "SBY-01",
    "SBY-02",
    "SBY-03",
    "SBY-04",
    "MLG-01",
  ];
  const channels: Array<"Gofood" | "Grabfood" | "ShopeeFood" | "Dine-in">[] = [
    ["Gofood"],
    ["Grabfood"],
    ["ShopeeFood"],
    ["Dine-in"],
    ["Gofood"],
    ["Gofood"],
    ["Gofood"],
    ["ShopeeFood"],
    ["Dine-in"],
    ["Grabfood"],
    ["Gofood"],
    ["ShopeeFood"],
    ["Dine-in"],
    ["Grabfood"],
    ["Gofood"],
    ["Gofood"],
    ["Grabfood"],
    ["ShopeeFood"],
    ["Dine-in"],
    ["Gofood"],
    ["Grabfood"],
    ["ShopeeFood"],
    ["Dine-in"],
    ["Gofood"],
    ["Grabfood"],
    ["ShopeeFood"],
    ["Dine-in"],
    ["Gofood"],
    ["Grabfood"],
    ["ShopeeFood"],
    ["Gofood"],
    ["Grabfood"],
    ["ShopeeFood"],
    ["Dine-in"],
    ["Gofood"],
  ];
  const recipes = [
    "rec-01",
    "rec-02",
    "rec-03",
    "rec-01+rec-04",
    "rec-06",
    "rec-01",
    "rec-03",
    "rec-02",
    "rec-07",
    "rec-08",
    "rec-01",
    "rec-09",
    "rec-10",
    "rec-01",
    "rec-02",
    "rec-03",
    "rec-04",
    "rec-05",
    "rec-06",
    "rec-07",
    "rec-08",
    "rec-09",
    "rec-10",
    "rec-01",
    "rec-02",
    "rec-03",
    "rec-04",
    "rec-05",
    "rec-06",
    "rec-07",
    "rec-01",
    "rec-02",
    "rec-03",
    "rec-04",
    "rec-05",
  ];

  return Array.from({ length: 35 }, (_, i) => {
    const idx = i + 1;
    const branchCode = branches[i];
    const channel = channels[i][0];
    const recipeIds = recipes[i].split("+");
    const daysAgo = idx <= 30 ? 10 - Math.floor((idx - 1) % 10) : 0;
    const isNew = idx >= 31;
    const basePrice = [
      35000, 48000, 42000, 60000, 38000, 35000, 42000, 48000, 36000, 52000, 35000, 15000, 22000,
      35000, 48000, 42000, 25000, 12000, 38000, 36000, 52000, 15000, 22000, 35000, 48000, 42000,
      25000, 12000, 38000, 36000, 35000, 48000, 42000, 25000, 12000,
    ][i];
    const qty = [
      2, 1, 1, 2, 2, 3, 2, 1, 2, 1, 4, 3, 5, 2, 1, 1, 2, 3, 1, 2, 1, 4, 2, 1, 2, 3, 1, 5, 2, 1, 2,
      1, 1, 2, 3,
    ][i];
    const cogs = Math.round(basePrice * 0.4);
    const subtotal = basePrice * qty;
    const tax = Math.round(subtotal * 0.1);
    const totalCogs = cogs * qty;
    const mdrFee = channel === "Dine-in" ? 0 : Math.round(subtotal * 0.2);
    const netSales = subtotal - (channel === "Dine-in" ? 0 : mdrFee);

    // Build order code
    const chCode =
      channel === "Gofood"
        ? "GF"
        : channel === "Grabfood"
          ? "GR"
          : channel === "ShopeeFood"
            ? "SF"
            : "DI";
    const orderCode = isNew ? `${chCode}-NEW-${idx - 30}` : `${chCode}-${100 + idx}`;

    const items = recipeIds.map((rId, j) => ({
      recipeProtoId: rId,
      quantity: j === 0 ? qty : Math.ceil(qty / 2), // distribute qty for multi-recipe orders
      price:
        [
          35000, 48000, 42000, 25000, 38000, 35000, 42000, 48000, 36000, 52000, 35000, 15000, 22000,
          35000, 48000, 42000, 25000, 12000, 38000, 36000, 52000, 15000, 22000, 35000, 48000, 42000,
          25000, 12000, 38000, 36000, 35000, 48000, 42000, 25000, 12000,
        ][recipeIds.indexOf(rId) + i] || basePrice,
      cogsAtTransaction: Math.round(
        ([
          35000, 48000, 42000, 25000, 38000, 35000, 42000, 48000, 36000, 52000, 35000, 15000, 22000,
          35000, 48000, 42000, 25000, 12000, 38000, 36000, 52000, 15000, 22000, 35000, 48000, 42000,
          25000, 12000, 38000, 36000, 35000, 48000, 42000, 25000, 12000,
        ][recipeIds.indexOf(rId) + i] || basePrice) * 0.4,
      ),
      brandProtoId: "brand-1",
    }));

    return {
      idx,
      branchCode,
      channel,
      status: isNew ? ("New" as const) : ("Completed" as const),
      subtotal,
      merchantDiscount: 0,
      platformDiscount: 0,
      taxAmount: tax,
      totalAmount: subtotal + tax,
      totalCogs,
      mdrFee,
      netSales,
      orderCode,
      createdAt: nDaysAgo(daysAgo),
      items,
    };
  });
})();
