/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AboutRouteImport } from './routes/about'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as DemoTanstackQueryRouteImport } from './routes/demo/tanstack-query'
import { Route as DemoTableRouteImport } from './routes/demo/table'
import { Route as DemoBetterAuthRouteImport } from './routes/demo/better-auth'
import { Route as ApiSetupRouteImport } from './routes/api/setup'
import { Route as ApiSeedDataRouteImport } from './routes/api/seed-data'
import { Route as ApiSeedRouteImport } from './routes/api/seed'
import { Route as LayoutYieldTrackingRouteImport } from './routes/_layout/yield-tracking'
import { Route as LayoutSettingsRouteImport } from './routes/_layout/settings'
import { Route as LayoutPrintRequestsRouteImport } from './routes/_layout/print-requests'
import { Route as LayoutPosRouteImport } from './routes/_layout/pos'
import { Route as LayoutPencatatanManualRouteImport } from './routes/_layout/pencatatan-manual'
import { Route as LayoutOrderHistoryRouteImport } from './routes/_layout/order-history'
import { Route as LayoutDataPenjualanRouteImport } from './routes/_layout/data-penjualan'
import { Route as LayoutDashboardRouteImport } from './routes/_layout/dashboard'
import { Route as LayoutCancelRequestsRouteImport } from './routes/_layout/cancel-requests'
import { Route as LayoutAuditInventoryRouteImport } from './routes/_layout/audit-inventory'
import { Route as LayoutWasteIndexRouteImport } from './routes/_layout/waste/index'
import { Route as LayoutSupplierDeliveriesIndexRouteImport } from './routes/_layout/supplier-deliveries/index'
import { Route as LayoutStockTransfersIndexRouteImport } from './routes/_layout/stock-transfers/index'
import { Route as LayoutStockOpnameIndexRouteImport } from './routes/_layout/stock-opname/index'
import { Route as LayoutScmTransfersIndexRouteImport } from './routes/_layout/scm-transfers/index'
import { Route as LayoutScmProcurementsIndexRouteImport } from './routes/_layout/scm-procurements/index'
import { Route as LayoutScmInvoicesIndexRouteImport } from './routes/_layout/scm-invoices/index'
import { Route as LayoutRecipesIndexRouteImport } from './routes/_layout/recipes/index'
import { Route as LayoutPurchaseRequisitionsIndexRouteImport } from './routes/_layout/purchase-requisitions/index'
import { Route as LayoutPurchaseOrdersIndexRouteImport } from './routes/_layout/purchase-orders/index'
import { Route as LayoutPeriodControlIndexRouteImport } from './routes/_layout/period-control/index'
import { Route as LayoutModifierGroupsIndexRouteImport } from './routes/_layout/modifier-groups/index'
import { Route as LayoutInventoryIndexRouteImport } from './routes/_layout/inventory/index'
import { Route as LayoutIngredientsIndexRouteImport } from './routes/_layout/ingredients/index'
import { Route as LayoutFinanceIndexRouteImport } from './routes/_layout/finance/index'
import { Route as LayoutDocsIndexRouteImport } from './routes/_layout/docs/index'
import { Route as LayoutDeliveryNotesIndexRouteImport } from './routes/_layout/delivery-notes/index'
import { Route as LayoutCategoriesIndexRouteImport } from './routes/_layout/categories/index'
import { Route as LayoutAnalyticsIndexRouteImport } from './routes/_layout/analytics/index'
import { Route as LayoutAdminIndexRouteImport } from './routes/_layout/admin/index'
import { Route as DemoFormSimpleRouteImport } from './routes/demo/form.simple'
import { Route as DemoFormAddressRouteImport } from './routes/demo/form.address'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as LayoutStockTransfersTrIdRouteImport } from './routes/_layout/stock-transfers/$trId'
import { Route as LayoutStockOpnameSoIdRouteImport } from './routes/_layout/stock-opname/$soId'
import { Route as LayoutScmTransfersNewRouteImport } from './routes/_layout/scm-transfers/new'
import { Route as LayoutScmTransfersTransferIdRouteImport } from './routes/_layout/scm-transfers/$transferId'
import { Route as LayoutScmProcurementsNewRouteImport } from './routes/_layout/scm-procurements/new'
import { Route as LayoutScmProcurementsProcurementIdRouteImport } from './routes/_layout/scm-procurements/$procurementId'
import { Route as LayoutScmInvoicesInvIdRouteImport } from './routes/_layout/scm-invoices/$invId'
import { Route as LayoutRecipesRecipeIdRouteImport } from './routes/_layout/recipes/$recipeId'
import { Route as LayoutPurchaseRequisitionsPrIdRouteImport } from './routes/_layout/purchase-requisitions/$prId'
import { Route as LayoutPurchaseOrdersPoIdRouteImport } from './routes/_layout/purchase-orders/$poId'
import { Route as LayoutPeriodControlPeriodIdRouteImport } from './routes/_layout/period-control/$periodId'
import { Route as LayoutModifierGroupsMgIdRouteImport } from './routes/_layout/modifier-groups/$mgId'
import { Route as LayoutInventoryLedgerRouteImport } from './routes/_layout/inventory/ledger'
import { Route as LayoutIngredientsIngIdRouteImport } from './routes/_layout/ingredients/$ingId'
import { Route as LayoutFinanceReconciliationRouteImport } from './routes/_layout/finance/reconciliation'
import { Route as LayoutFinanceBrokenStockRouteImport } from './routes/_layout/finance/broken-stock'
import { Route as LayoutDocsStokOpnameRouteImport } from './routes/_layout/docs/stok-opname'
import { Route as LayoutDocsResepDanPosRouteImport } from './routes/_layout/docs/resep-dan-pos'
import { Route as LayoutDocsProduksiInternalRouteImport } from './routes/_layout/docs/produksi-internal'
import { Route as LayoutDocsPengadaanRouteImport } from './routes/_layout/docs/pengadaan'
import { Route as LayoutDocsMutasiStokRouteImport } from './routes/_layout/docs/mutasi-stok'
import { Route as LayoutDocsKartuStokRouteImport } from './routes/_layout/docs/kartu-stok'
import { Route as LayoutDocsBarangMasukRouteImport } from './routes/_layout/docs/barang-masuk'
import { Route as LayoutDeliveryNotesDnIdRouteImport } from './routes/_layout/delivery-notes/$dnId'
import { Route as LayoutCategoriesCategoryIdRouteImport } from './routes/_layout/categories/$categoryId'
import { Route as LayoutAnalyticsSalesRouteImport } from './routes/_layout/analytics/sales'
import { Route as LayoutAnalyticsInventoryRouteImport } from './routes/_layout/analytics/inventory'
import { Route as LayoutAdminVouchersRouteImport } from './routes/_layout/admin/vouchers'
import { Route as LayoutAdminUsersRouteImport } from './routes/_layout/admin/users'
import { Route as LayoutAdminSystemLogsRouteImport } from './routes/_layout/admin/system-logs'
import { Route as LayoutAdminSalesRouteImport } from './routes/_layout/admin/sales'
import { Route as LayoutAdminPlatformFeesRouteImport } from './routes/_layout/admin/platform-fees'
import { Route as LayoutAdminBrandsRouteImport } from './routes/_layout/admin/brands'
import { Route as LayoutAdminBranchesRouteImport } from './routes/_layout/admin/branches'
import { Route as LayoutAdminAuditLogsRouteImport } from './routes/_layout/admin/audit-logs'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const DemoTanstackQueryRoute = DemoTanstackQueryRouteImport.update({
  id: '/demo/tanstack-query',
  path: '/demo/tanstack-query',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoTableRoute = DemoTableRouteImport.update({
  id: '/demo/table',
  path: '/demo/table',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoBetterAuthRoute = DemoBetterAuthRouteImport.update({
  id: '/demo/better-auth',
  path: '/demo/better-auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSetupRoute = ApiSetupRouteImport.update({
  id: '/api/setup',
  path: '/api/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSeedDataRoute = ApiSeedDataRouteImport.update({
  id: '/api/seed-data',
  path: '/api/seed-data',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSeedRoute = ApiSeedRouteImport.update({
  id: '/api/seed',
  path: '/api/seed',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutYieldTrackingRoute = LayoutYieldTrackingRouteImport.update({
  id: '/yield-tracking',
  path: '/yield-tracking',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSettingsRoute = LayoutSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutPrintRequestsRoute = LayoutPrintRequestsRouteImport.update({
  id: '/print-requests',
  path: '/print-requests',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutPosRoute = LayoutPosRouteImport.update({
  id: '/pos',
  path: '/pos',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutPencatatanManualRoute = LayoutPencatatanManualRouteImport.update({
  id: '/pencatatan-manual',
  path: '/pencatatan-manual',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutOrderHistoryRoute = LayoutOrderHistoryRouteImport.update({
  id: '/order-history',
  path: '/order-history',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutDataPenjualanRoute = LayoutDataPenjualanRouteImport.update({
  id: '/data-penjualan',
  path: '/data-penjualan',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutDashboardRoute = LayoutDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutCancelRequestsRoute = LayoutCancelRequestsRouteImport.update({
  id: '/cancel-requests',
  path: '/cancel-requests',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAuditInventoryRoute = LayoutAuditInventoryRouteImport.update({
  id: '/audit-inventory',
  path: '/audit-inventory',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutWasteIndexRoute = LayoutWasteIndexRouteImport.update({
  id: '/waste/',
  path: '/waste/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSupplierDeliveriesIndexRoute =
  LayoutSupplierDeliveriesIndexRouteImport.update({
    id: '/supplier-deliveries/',
    path: '/supplier-deliveries/',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutStockTransfersIndexRoute =
  LayoutStockTransfersIndexRouteImport.update({
    id: '/stock-transfers/',
    path: '/stock-transfers/',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutStockOpnameIndexRoute = LayoutStockOpnameIndexRouteImport.update({
  id: '/stock-opname/',
  path: '/stock-opname/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutScmTransfersIndexRoute = LayoutScmTransfersIndexRouteImport.update({
  id: '/scm-transfers/',
  path: '/scm-transfers/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutScmProcurementsIndexRoute =
  LayoutScmProcurementsIndexRouteImport.update({
    id: '/scm-procurements/',
    path: '/scm-procurements/',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutScmInvoicesIndexRoute = LayoutScmInvoicesIndexRouteImport.update({
  id: '/scm-invoices/',
  path: '/scm-invoices/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutRecipesIndexRoute = LayoutRecipesIndexRouteImport.update({
  id: '/recipes/',
  path: '/recipes/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutPurchaseRequisitionsIndexRoute =
  LayoutPurchaseRequisitionsIndexRouteImport.update({
    id: '/purchase-requisitions/',
    path: '/purchase-requisitions/',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutPurchaseOrdersIndexRoute =
  LayoutPurchaseOrdersIndexRouteImport.update({
    id: '/purchase-orders/',
    path: '/purchase-orders/',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutPeriodControlIndexRoute =
  LayoutPeriodControlIndexRouteImport.update({
    id: '/period-control/',
    path: '/period-control/',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutModifierGroupsIndexRoute =
  LayoutModifierGroupsIndexRouteImport.update({
    id: '/modifier-groups/',
    path: '/modifier-groups/',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutInventoryIndexRoute = LayoutInventoryIndexRouteImport.update({
  id: '/inventory/',
  path: '/inventory/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutIngredientsIndexRoute = LayoutIngredientsIndexRouteImport.update({
  id: '/ingredients/',
  path: '/ingredients/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutFinanceIndexRoute = LayoutFinanceIndexRouteImport.update({
  id: '/finance/',
  path: '/finance/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutDocsIndexRoute = LayoutDocsIndexRouteImport.update({
  id: '/docs/',
  path: '/docs/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutDeliveryNotesIndexRoute =
  LayoutDeliveryNotesIndexRouteImport.update({
    id: '/delivery-notes/',
    path: '/delivery-notes/',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutCategoriesIndexRoute = LayoutCategoriesIndexRouteImport.update({
  id: '/categories/',
  path: '/categories/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAnalyticsIndexRoute = LayoutAnalyticsIndexRouteImport.update({
  id: '/analytics/',
  path: '/analytics/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAdminIndexRoute = LayoutAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => LayoutRoute,
} as any)
const DemoFormSimpleRoute = DemoFormSimpleRouteImport.update({
  id: '/demo/form/simple',
  path: '/demo/form/simple',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoFormAddressRoute = DemoFormAddressRouteImport.update({
  id: '/demo/form/address',
  path: '/demo/form/address',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutStockTransfersTrIdRoute =
  LayoutStockTransfersTrIdRouteImport.update({
    id: '/stock-transfers/$trId',
    path: '/stock-transfers/$trId',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutStockOpnameSoIdRoute = LayoutStockOpnameSoIdRouteImport.update({
  id: '/stock-opname/$soId',
  path: '/stock-opname/$soId',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutScmTransfersNewRoute = LayoutScmTransfersNewRouteImport.update({
  id: '/scm-transfers/new',
  path: '/scm-transfers/new',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutScmTransfersTransferIdRoute =
  LayoutScmTransfersTransferIdRouteImport.update({
    id: '/scm-transfers/$transferId',
    path: '/scm-transfers/$transferId',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutScmProcurementsNewRoute =
  LayoutScmProcurementsNewRouteImport.update({
    id: '/scm-procurements/new',
    path: '/scm-procurements/new',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutScmProcurementsProcurementIdRoute =
  LayoutScmProcurementsProcurementIdRouteImport.update({
    id: '/scm-procurements/$procurementId',
    path: '/scm-procurements/$procurementId',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutScmInvoicesInvIdRoute = LayoutScmInvoicesInvIdRouteImport.update({
  id: '/scm-invoices/$invId',
  path: '/scm-invoices/$invId',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutRecipesRecipeIdRoute = LayoutRecipesRecipeIdRouteImport.update({
  id: '/recipes/$recipeId',
  path: '/recipes/$recipeId',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutPurchaseRequisitionsPrIdRoute =
  LayoutPurchaseRequisitionsPrIdRouteImport.update({
    id: '/purchase-requisitions/$prId',
    path: '/purchase-requisitions/$prId',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutPurchaseOrdersPoIdRoute =
  LayoutPurchaseOrdersPoIdRouteImport.update({
    id: '/purchase-orders/$poId',
    path: '/purchase-orders/$poId',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutPeriodControlPeriodIdRoute =
  LayoutPeriodControlPeriodIdRouteImport.update({
    id: '/period-control/$periodId',
    path: '/period-control/$periodId',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutModifierGroupsMgIdRoute =
  LayoutModifierGroupsMgIdRouteImport.update({
    id: '/modifier-groups/$mgId',
    path: '/modifier-groups/$mgId',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutInventoryLedgerRoute = LayoutInventoryLedgerRouteImport.update({
  id: '/inventory/ledger',
  path: '/inventory/ledger',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutIngredientsIngIdRoute = LayoutIngredientsIngIdRouteImport.update({
  id: '/ingredients/$ingId',
  path: '/ingredients/$ingId',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutFinanceReconciliationRoute =
  LayoutFinanceReconciliationRouteImport.update({
    id: '/finance/reconciliation',
    path: '/finance/reconciliation',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutFinanceBrokenStockRoute =
  LayoutFinanceBrokenStockRouteImport.update({
    id: '/finance/broken-stock',
    path: '/finance/broken-stock',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutDocsStokOpnameRoute = LayoutDocsStokOpnameRouteImport.update({
  id: '/docs/stok-opname',
  path: '/docs/stok-opname',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutDocsResepDanPosRoute = LayoutDocsResepDanPosRouteImport.update({
  id: '/docs/resep-dan-pos',
  path: '/docs/resep-dan-pos',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutDocsProduksiInternalRoute =
  LayoutDocsProduksiInternalRouteImport.update({
    id: '/docs/produksi-internal',
    path: '/docs/produksi-internal',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutDocsPengadaanRoute = LayoutDocsPengadaanRouteImport.update({
  id: '/docs/pengadaan',
  path: '/docs/pengadaan',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutDocsMutasiStokRoute = LayoutDocsMutasiStokRouteImport.update({
  id: '/docs/mutasi-stok',
  path: '/docs/mutasi-stok',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutDocsKartuStokRoute = LayoutDocsKartuStokRouteImport.update({
  id: '/docs/kartu-stok',
  path: '/docs/kartu-stok',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutDocsBarangMasukRoute = LayoutDocsBarangMasukRouteImport.update({
  id: '/docs/barang-masuk',
  path: '/docs/barang-masuk',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutDeliveryNotesDnIdRoute = LayoutDeliveryNotesDnIdRouteImport.update({
  id: '/delivery-notes/$dnId',
  path: '/delivery-notes/$dnId',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutCategoriesCategoryIdRoute =
  LayoutCategoriesCategoryIdRouteImport.update({
    id: '/categories/$categoryId',
    path: '/categories/$categoryId',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutAnalyticsSalesRoute = LayoutAnalyticsSalesRouteImport.update({
  id: '/analytics/sales',
  path: '/analytics/sales',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAnalyticsInventoryRoute =
  LayoutAnalyticsInventoryRouteImport.update({
    id: '/analytics/inventory',
    path: '/analytics/inventory',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutAdminVouchersRoute = LayoutAdminVouchersRouteImport.update({
  id: '/admin/vouchers',
  path: '/admin/vouchers',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAdminUsersRoute = LayoutAdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAdminSystemLogsRoute = LayoutAdminSystemLogsRouteImport.update({
  id: '/admin/system-logs',
  path: '/admin/system-logs',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAdminSalesRoute = LayoutAdminSalesRouteImport.update({
  id: '/admin/sales',
  path: '/admin/sales',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAdminPlatformFeesRoute = LayoutAdminPlatformFeesRouteImport.update({
  id: '/admin/platform-fees',
  path: '/admin/platform-fees',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAdminBrandsRoute = LayoutAdminBrandsRouteImport.update({
  id: '/admin/brands',
  path: '/admin/brands',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAdminBranchesRoute = LayoutAdminBranchesRouteImport.update({
  id: '/admin/branches',
  path: '/admin/branches',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAdminAuditLogsRoute = LayoutAdminAuditLogsRouteImport.update({
  id: '/admin/audit-logs',
  path: '/admin/audit-logs',
  getParentRoute: () => LayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof LayoutIndexRoute
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/audit-inventory': typeof LayoutAuditInventoryRoute
  '/cancel-requests': typeof LayoutCancelRequestsRoute
  '/dashboard': typeof LayoutDashboardRoute
  '/data-penjualan': typeof LayoutDataPenjualanRoute
  '/order-history': typeof LayoutOrderHistoryRoute
  '/pencatatan-manual': typeof LayoutPencatatanManualRoute
  '/pos': typeof LayoutPosRoute
  '/print-requests': typeof LayoutPrintRequestsRoute
  '/settings': typeof LayoutSettingsRoute
  '/yield-tracking': typeof LayoutYieldTrackingRoute
  '/api/seed': typeof ApiSeedRoute
  '/api/seed-data': typeof ApiSeedDataRoute
  '/api/setup': typeof ApiSetupRoute
  '/demo/better-auth': typeof DemoBetterAuthRoute
  '/demo/table': typeof DemoTableRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/admin/audit-logs': typeof LayoutAdminAuditLogsRoute
  '/admin/branches': typeof LayoutAdminBranchesRoute
  '/admin/brands': typeof LayoutAdminBrandsRoute
  '/admin/platform-fees': typeof LayoutAdminPlatformFeesRoute
  '/admin/sales': typeof LayoutAdminSalesRoute
  '/admin/system-logs': typeof LayoutAdminSystemLogsRoute
  '/admin/users': typeof LayoutAdminUsersRoute
  '/admin/vouchers': typeof LayoutAdminVouchersRoute
  '/analytics/inventory': typeof LayoutAnalyticsInventoryRoute
  '/analytics/sales': typeof LayoutAnalyticsSalesRoute
  '/categories/$categoryId': typeof LayoutCategoriesCategoryIdRoute
  '/delivery-notes/$dnId': typeof LayoutDeliveryNotesDnIdRoute
  '/docs/barang-masuk': typeof LayoutDocsBarangMasukRoute
  '/docs/kartu-stok': typeof LayoutDocsKartuStokRoute
  '/docs/mutasi-stok': typeof LayoutDocsMutasiStokRoute
  '/docs/pengadaan': typeof LayoutDocsPengadaanRoute
  '/docs/produksi-internal': typeof LayoutDocsProduksiInternalRoute
  '/docs/resep-dan-pos': typeof LayoutDocsResepDanPosRoute
  '/docs/stok-opname': typeof LayoutDocsStokOpnameRoute
  '/finance/broken-stock': typeof LayoutFinanceBrokenStockRoute
  '/finance/reconciliation': typeof LayoutFinanceReconciliationRoute
  '/ingredients/$ingId': typeof LayoutIngredientsIngIdRoute
  '/inventory/ledger': typeof LayoutInventoryLedgerRoute
  '/modifier-groups/$mgId': typeof LayoutModifierGroupsMgIdRoute
  '/period-control/$periodId': typeof LayoutPeriodControlPeriodIdRoute
  '/purchase-orders/$poId': typeof LayoutPurchaseOrdersPoIdRoute
  '/purchase-requisitions/$prId': typeof LayoutPurchaseRequisitionsPrIdRoute
  '/recipes/$recipeId': typeof LayoutRecipesRecipeIdRoute
  '/scm-invoices/$invId': typeof LayoutScmInvoicesInvIdRoute
  '/scm-procurements/$procurementId': typeof LayoutScmProcurementsProcurementIdRoute
  '/scm-procurements/new': typeof LayoutScmProcurementsNewRoute
  '/scm-transfers/$transferId': typeof LayoutScmTransfersTransferIdRoute
  '/scm-transfers/new': typeof LayoutScmTransfersNewRoute
  '/stock-opname/$soId': typeof LayoutStockOpnameSoIdRoute
  '/stock-transfers/$trId': typeof LayoutStockTransfersTrIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/demo/form/address': typeof DemoFormAddressRoute
  '/demo/form/simple': typeof DemoFormSimpleRoute
  '/admin/': typeof LayoutAdminIndexRoute
  '/analytics/': typeof LayoutAnalyticsIndexRoute
  '/categories/': typeof LayoutCategoriesIndexRoute
  '/delivery-notes/': typeof LayoutDeliveryNotesIndexRoute
  '/docs/': typeof LayoutDocsIndexRoute
  '/finance/': typeof LayoutFinanceIndexRoute
  '/ingredients/': typeof LayoutIngredientsIndexRoute
  '/inventory/': typeof LayoutInventoryIndexRoute
  '/modifier-groups/': typeof LayoutModifierGroupsIndexRoute
  '/period-control/': typeof LayoutPeriodControlIndexRoute
  '/purchase-orders/': typeof LayoutPurchaseOrdersIndexRoute
  '/purchase-requisitions/': typeof LayoutPurchaseRequisitionsIndexRoute
  '/recipes/': typeof LayoutRecipesIndexRoute
  '/scm-invoices/': typeof LayoutScmInvoicesIndexRoute
  '/scm-procurements/': typeof LayoutScmProcurementsIndexRoute
  '/scm-transfers/': typeof LayoutScmTransfersIndexRoute
  '/stock-opname/': typeof LayoutStockOpnameIndexRoute
  '/stock-transfers/': typeof LayoutStockTransfersIndexRoute
  '/supplier-deliveries/': typeof LayoutSupplierDeliveriesIndexRoute
  '/waste/': typeof LayoutWasteIndexRoute
}
export interface FileRoutesByTo {
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/audit-inventory': typeof LayoutAuditInventoryRoute
  '/cancel-requests': typeof LayoutCancelRequestsRoute
  '/dashboard': typeof LayoutDashboardRoute
  '/data-penjualan': typeof LayoutDataPenjualanRoute
  '/order-history': typeof LayoutOrderHistoryRoute
  '/pencatatan-manual': typeof LayoutPencatatanManualRoute
  '/pos': typeof LayoutPosRoute
  '/print-requests': typeof LayoutPrintRequestsRoute
  '/settings': typeof LayoutSettingsRoute
  '/yield-tracking': typeof LayoutYieldTrackingRoute
  '/api/seed': typeof ApiSeedRoute
  '/api/seed-data': typeof ApiSeedDataRoute
  '/api/setup': typeof ApiSetupRoute
  '/demo/better-auth': typeof DemoBetterAuthRoute
  '/demo/table': typeof DemoTableRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/': typeof LayoutIndexRoute
  '/admin/audit-logs': typeof LayoutAdminAuditLogsRoute
  '/admin/branches': typeof LayoutAdminBranchesRoute
  '/admin/brands': typeof LayoutAdminBrandsRoute
  '/admin/platform-fees': typeof LayoutAdminPlatformFeesRoute
  '/admin/sales': typeof LayoutAdminSalesRoute
  '/admin/system-logs': typeof LayoutAdminSystemLogsRoute
  '/admin/users': typeof LayoutAdminUsersRoute
  '/admin/vouchers': typeof LayoutAdminVouchersRoute
  '/analytics/inventory': typeof LayoutAnalyticsInventoryRoute
  '/analytics/sales': typeof LayoutAnalyticsSalesRoute
  '/categories/$categoryId': typeof LayoutCategoriesCategoryIdRoute
  '/delivery-notes/$dnId': typeof LayoutDeliveryNotesDnIdRoute
  '/docs/barang-masuk': typeof LayoutDocsBarangMasukRoute
  '/docs/kartu-stok': typeof LayoutDocsKartuStokRoute
  '/docs/mutasi-stok': typeof LayoutDocsMutasiStokRoute
  '/docs/pengadaan': typeof LayoutDocsPengadaanRoute
  '/docs/produksi-internal': typeof LayoutDocsProduksiInternalRoute
  '/docs/resep-dan-pos': typeof LayoutDocsResepDanPosRoute
  '/docs/stok-opname': typeof LayoutDocsStokOpnameRoute
  '/finance/broken-stock': typeof LayoutFinanceBrokenStockRoute
  '/finance/reconciliation': typeof LayoutFinanceReconciliationRoute
  '/ingredients/$ingId': typeof LayoutIngredientsIngIdRoute
  '/inventory/ledger': typeof LayoutInventoryLedgerRoute
  '/modifier-groups/$mgId': typeof LayoutModifierGroupsMgIdRoute
  '/period-control/$periodId': typeof LayoutPeriodControlPeriodIdRoute
  '/purchase-orders/$poId': typeof LayoutPurchaseOrdersPoIdRoute
  '/purchase-requisitions/$prId': typeof LayoutPurchaseRequisitionsPrIdRoute
  '/recipes/$recipeId': typeof LayoutRecipesRecipeIdRoute
  '/scm-invoices/$invId': typeof LayoutScmInvoicesInvIdRoute
  '/scm-procurements/$procurementId': typeof LayoutScmProcurementsProcurementIdRoute
  '/scm-procurements/new': typeof LayoutScmProcurementsNewRoute
  '/scm-transfers/$transferId': typeof LayoutScmTransfersTransferIdRoute
  '/scm-transfers/new': typeof LayoutScmTransfersNewRoute
  '/stock-opname/$soId': typeof LayoutStockOpnameSoIdRoute
  '/stock-transfers/$trId': typeof LayoutStockTransfersTrIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/demo/form/address': typeof DemoFormAddressRoute
  '/demo/form/simple': typeof DemoFormSimpleRoute
  '/admin': typeof LayoutAdminIndexRoute
  '/analytics': typeof LayoutAnalyticsIndexRoute
  '/categories': typeof LayoutCategoriesIndexRoute
  '/delivery-notes': typeof LayoutDeliveryNotesIndexRoute
  '/docs': typeof LayoutDocsIndexRoute
  '/finance': typeof LayoutFinanceIndexRoute
  '/ingredients': typeof LayoutIngredientsIndexRoute
  '/inventory': typeof LayoutInventoryIndexRoute
  '/modifier-groups': typeof LayoutModifierGroupsIndexRoute
  '/period-control': typeof LayoutPeriodControlIndexRoute
  '/purchase-orders': typeof LayoutPurchaseOrdersIndexRoute
  '/purchase-requisitions': typeof LayoutPurchaseRequisitionsIndexRoute
  '/recipes': typeof LayoutRecipesIndexRoute
  '/scm-invoices': typeof LayoutScmInvoicesIndexRoute
  '/scm-procurements': typeof LayoutScmProcurementsIndexRoute
  '/scm-transfers': typeof LayoutScmTransfersIndexRoute
  '/stock-opname': typeof LayoutStockOpnameIndexRoute
  '/stock-transfers': typeof LayoutStockTransfersIndexRoute
  '/supplier-deliveries': typeof LayoutSupplierDeliveriesIndexRoute
  '/waste': typeof LayoutWasteIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/_layout/audit-inventory': typeof LayoutAuditInventoryRoute
  '/_layout/cancel-requests': typeof LayoutCancelRequestsRoute
  '/_layout/dashboard': typeof LayoutDashboardRoute
  '/_layout/data-penjualan': typeof LayoutDataPenjualanRoute
  '/_layout/order-history': typeof LayoutOrderHistoryRoute
  '/_layout/pencatatan-manual': typeof LayoutPencatatanManualRoute
  '/_layout/pos': typeof LayoutPosRoute
  '/_layout/print-requests': typeof LayoutPrintRequestsRoute
  '/_layout/settings': typeof LayoutSettingsRoute
  '/_layout/yield-tracking': typeof LayoutYieldTrackingRoute
  '/api/seed': typeof ApiSeedRoute
  '/api/seed-data': typeof ApiSeedDataRoute
  '/api/setup': typeof ApiSetupRoute
  '/demo/better-auth': typeof DemoBetterAuthRoute
  '/demo/table': typeof DemoTableRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/_layout/': typeof LayoutIndexRoute
  '/_layout/admin/audit-logs': typeof LayoutAdminAuditLogsRoute
  '/_layout/admin/branches': typeof LayoutAdminBranchesRoute
  '/_layout/admin/brands': typeof LayoutAdminBrandsRoute
  '/_layout/admin/platform-fees': typeof LayoutAdminPlatformFeesRoute
  '/_layout/admin/sales': typeof LayoutAdminSalesRoute
  '/_layout/admin/system-logs': typeof LayoutAdminSystemLogsRoute
  '/_layout/admin/users': typeof LayoutAdminUsersRoute
  '/_layout/admin/vouchers': typeof LayoutAdminVouchersRoute
  '/_layout/analytics/inventory': typeof LayoutAnalyticsInventoryRoute
  '/_layout/analytics/sales': typeof LayoutAnalyticsSalesRoute
  '/_layout/categories/$categoryId': typeof LayoutCategoriesCategoryIdRoute
  '/_layout/delivery-notes/$dnId': typeof LayoutDeliveryNotesDnIdRoute
  '/_layout/docs/barang-masuk': typeof LayoutDocsBarangMasukRoute
  '/_layout/docs/kartu-stok': typeof LayoutDocsKartuStokRoute
  '/_layout/docs/mutasi-stok': typeof LayoutDocsMutasiStokRoute
  '/_layout/docs/pengadaan': typeof LayoutDocsPengadaanRoute
  '/_layout/docs/produksi-internal': typeof LayoutDocsProduksiInternalRoute
  '/_layout/docs/resep-dan-pos': typeof LayoutDocsResepDanPosRoute
  '/_layout/docs/stok-opname': typeof LayoutDocsStokOpnameRoute
  '/_layout/finance/broken-stock': typeof LayoutFinanceBrokenStockRoute
  '/_layout/finance/reconciliation': typeof LayoutFinanceReconciliationRoute
  '/_layout/ingredients/$ingId': typeof LayoutIngredientsIngIdRoute
  '/_layout/inventory/ledger': typeof LayoutInventoryLedgerRoute
  '/_layout/modifier-groups/$mgId': typeof LayoutModifierGroupsMgIdRoute
  '/_layout/period-control/$periodId': typeof LayoutPeriodControlPeriodIdRoute
  '/_layout/purchase-orders/$poId': typeof LayoutPurchaseOrdersPoIdRoute
  '/_layout/purchase-requisitions/$prId': typeof LayoutPurchaseRequisitionsPrIdRoute
  '/_layout/recipes/$recipeId': typeof LayoutRecipesRecipeIdRoute
  '/_layout/scm-invoices/$invId': typeof LayoutScmInvoicesInvIdRoute
  '/_layout/scm-procurements/$procurementId': typeof LayoutScmProcurementsProcurementIdRoute
  '/_layout/scm-procurements/new': typeof LayoutScmProcurementsNewRoute
  '/_layout/scm-transfers/$transferId': typeof LayoutScmTransfersTransferIdRoute
  '/_layout/scm-transfers/new': typeof LayoutScmTransfersNewRoute
  '/_layout/stock-opname/$soId': typeof LayoutStockOpnameSoIdRoute
  '/_layout/stock-transfers/$trId': typeof LayoutStockTransfersTrIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/demo/form/address': typeof DemoFormAddressRoute
  '/demo/form/simple': typeof DemoFormSimpleRoute
  '/_layout/admin/': typeof LayoutAdminIndexRoute
  '/_layout/analytics/': typeof LayoutAnalyticsIndexRoute
  '/_layout/categories/': typeof LayoutCategoriesIndexRoute
  '/_layout/delivery-notes/': typeof LayoutDeliveryNotesIndexRoute
  '/_layout/docs/': typeof LayoutDocsIndexRoute
  '/_layout/finance/': typeof LayoutFinanceIndexRoute
  '/_layout/ingredients/': typeof LayoutIngredientsIndexRoute
  '/_layout/inventory/': typeof LayoutInventoryIndexRoute
  '/_layout/modifier-groups/': typeof LayoutModifierGroupsIndexRoute
  '/_layout/period-control/': typeof LayoutPeriodControlIndexRoute
  '/_layout/purchase-orders/': typeof LayoutPurchaseOrdersIndexRoute
  '/_layout/purchase-requisitions/': typeof LayoutPurchaseRequisitionsIndexRoute
  '/_layout/recipes/': typeof LayoutRecipesIndexRoute
  '/_layout/scm-invoices/': typeof LayoutScmInvoicesIndexRoute
  '/_layout/scm-procurements/': typeof LayoutScmProcurementsIndexRoute
  '/_layout/scm-transfers/': typeof LayoutScmTransfersIndexRoute
  '/_layout/stock-opname/': typeof LayoutStockOpnameIndexRoute
  '/_layout/stock-transfers/': typeof LayoutStockTransfersIndexRoute
  '/_layout/supplier-deliveries/': typeof LayoutSupplierDeliveriesIndexRoute
  '/_layout/waste/': typeof LayoutWasteIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/login'
    | '/audit-inventory'
    | '/cancel-requests'
    | '/dashboard'
    | '/data-penjualan'
    | '/order-history'
    | '/pencatatan-manual'
    | '/pos'
    | '/print-requests'
    | '/settings'
    | '/yield-tracking'
    | '/api/seed'
    | '/api/seed-data'
    | '/api/setup'
    | '/demo/better-auth'
    | '/demo/table'
    | '/demo/tanstack-query'
    | '/admin/audit-logs'
    | '/admin/branches'
    | '/admin/brands'
    | '/admin/platform-fees'
    | '/admin/sales'
    | '/admin/system-logs'
    | '/admin/users'
    | '/admin/vouchers'
    | '/analytics/inventory'
    | '/analytics/sales'
    | '/categories/$categoryId'
    | '/delivery-notes/$dnId'
    | '/docs/barang-masuk'
    | '/docs/kartu-stok'
    | '/docs/mutasi-stok'
    | '/docs/pengadaan'
    | '/docs/produksi-internal'
    | '/docs/resep-dan-pos'
    | '/docs/stok-opname'
    | '/finance/broken-stock'
    | '/finance/reconciliation'
    | '/ingredients/$ingId'
    | '/inventory/ledger'
    | '/modifier-groups/$mgId'
    | '/period-control/$periodId'
    | '/purchase-orders/$poId'
    | '/purchase-requisitions/$prId'
    | '/recipes/$recipeId'
    | '/scm-invoices/$invId'
    | '/scm-procurements/$procurementId'
    | '/scm-procurements/new'
    | '/scm-transfers/$transferId'
    | '/scm-transfers/new'
    | '/stock-opname/$soId'
    | '/stock-transfers/$trId'
    | '/api/auth/$'
    | '/demo/form/address'
    | '/demo/form/simple'
    | '/admin/'
    | '/analytics/'
    | '/categories/'
    | '/delivery-notes/'
    | '/docs/'
    | '/finance/'
    | '/ingredients/'
    | '/inventory/'
    | '/modifier-groups/'
    | '/period-control/'
    | '/purchase-orders/'
    | '/purchase-requisitions/'
    | '/recipes/'
    | '/scm-invoices/'
    | '/scm-procurements/'
    | '/scm-transfers/'
    | '/stock-opname/'
    | '/stock-transfers/'
    | '/supplier-deliveries/'
    | '/waste/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/about'
    | '/login'
    | '/audit-inventory'
    | '/cancel-requests'
    | '/dashboard'
    | '/data-penjualan'
    | '/order-history'
    | '/pencatatan-manual'
    | '/pos'
    | '/print-requests'
    | '/settings'
    | '/yield-tracking'
    | '/api/seed'
    | '/api/seed-data'
    | '/api/setup'
    | '/demo/better-auth'
    | '/demo/table'
    | '/demo/tanstack-query'
    | '/'
    | '/admin/audit-logs'
    | '/admin/branches'
    | '/admin/brands'
    | '/admin/platform-fees'
    | '/admin/sales'
    | '/admin/system-logs'
    | '/admin/users'
    | '/admin/vouchers'
    | '/analytics/inventory'
    | '/analytics/sales'
    | '/categories/$categoryId'
    | '/delivery-notes/$dnId'
    | '/docs/barang-masuk'
    | '/docs/kartu-stok'
    | '/docs/mutasi-stok'
    | '/docs/pengadaan'
    | '/docs/produksi-internal'
    | '/docs/resep-dan-pos'
    | '/docs/stok-opname'
    | '/finance/broken-stock'
    | '/finance/reconciliation'
    | '/ingredients/$ingId'
    | '/inventory/ledger'
    | '/modifier-groups/$mgId'
    | '/period-control/$periodId'
    | '/purchase-orders/$poId'
    | '/purchase-requisitions/$prId'
    | '/recipes/$recipeId'
    | '/scm-invoices/$invId'
    | '/scm-procurements/$procurementId'
    | '/scm-procurements/new'
    | '/scm-transfers/$transferId'
    | '/scm-transfers/new'
    | '/stock-opname/$soId'
    | '/stock-transfers/$trId'
    | '/api/auth/$'
    | '/demo/form/address'
    | '/demo/form/simple'
    | '/admin'
    | '/analytics'
    | '/categories'
    | '/delivery-notes'
    | '/docs'
    | '/finance'
    | '/ingredients'
    | '/inventory'
    | '/modifier-groups'
    | '/period-control'
    | '/purchase-orders'
    | '/purchase-requisitions'
    | '/recipes'
    | '/scm-invoices'
    | '/scm-procurements'
    | '/scm-transfers'
    | '/stock-opname'
    | '/stock-transfers'
    | '/supplier-deliveries'
    | '/waste'
  id:
    | '__root__'
    | '/_layout'
    | '/about'
    | '/login'
    | '/_layout/audit-inventory'
    | '/_layout/cancel-requests'
    | '/_layout/dashboard'
    | '/_layout/data-penjualan'
    | '/_layout/order-history'
    | '/_layout/pencatatan-manual'
    | '/_layout/pos'
    | '/_layout/print-requests'
    | '/_layout/settings'
    | '/_layout/yield-tracking'
    | '/api/seed'
    | '/api/seed-data'
    | '/api/setup'
    | '/demo/better-auth'
    | '/demo/table'
    | '/demo/tanstack-query'
    | '/_layout/'
    | '/_layout/admin/audit-logs'
    | '/_layout/admin/branches'
    | '/_layout/admin/brands'
    | '/_layout/admin/platform-fees'
    | '/_layout/admin/sales'
    | '/_layout/admin/system-logs'
    | '/_layout/admin/users'
    | '/_layout/admin/vouchers'
    | '/_layout/analytics/inventory'
    | '/_layout/analytics/sales'
    | '/_layout/categories/$categoryId'
    | '/_layout/delivery-notes/$dnId'
    | '/_layout/docs/barang-masuk'
    | '/_layout/docs/kartu-stok'
    | '/_layout/docs/mutasi-stok'
    | '/_layout/docs/pengadaan'
    | '/_layout/docs/produksi-internal'
    | '/_layout/docs/resep-dan-pos'
    | '/_layout/docs/stok-opname'
    | '/_layout/finance/broken-stock'
    | '/_layout/finance/reconciliation'
    | '/_layout/ingredients/$ingId'
    | '/_layout/inventory/ledger'
    | '/_layout/modifier-groups/$mgId'
    | '/_layout/period-control/$periodId'
    | '/_layout/purchase-orders/$poId'
    | '/_layout/purchase-requisitions/$prId'
    | '/_layout/recipes/$recipeId'
    | '/_layout/scm-invoices/$invId'
    | '/_layout/scm-procurements/$procurementId'
    | '/_layout/scm-procurements/new'
    | '/_layout/scm-transfers/$transferId'
    | '/_layout/scm-transfers/new'
    | '/_layout/stock-opname/$soId'
    | '/_layout/stock-transfers/$trId'
    | '/api/auth/$'
    | '/demo/form/address'
    | '/demo/form/simple'
    | '/_layout/admin/'
    | '/_layout/analytics/'
    | '/_layout/categories/'
    | '/_layout/delivery-notes/'
    | '/_layout/docs/'
    | '/_layout/finance/'
    | '/_layout/ingredients/'
    | '/_layout/inventory/'
    | '/_layout/modifier-groups/'
    | '/_layout/period-control/'
    | '/_layout/purchase-orders/'
    | '/_layout/purchase-requisitions/'
    | '/_layout/recipes/'
    | '/_layout/scm-invoices/'
    | '/_layout/scm-procurements/'
    | '/_layout/scm-transfers/'
    | '/_layout/stock-opname/'
    | '/_layout/stock-transfers/'
    | '/_layout/supplier-deliveries/'
    | '/_layout/waste/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  AboutRoute: typeof AboutRoute
  LoginRoute: typeof LoginRoute
  ApiSeedRoute: typeof ApiSeedRoute
  ApiSeedDataRoute: typeof ApiSeedDataRoute
  ApiSetupRoute: typeof ApiSetupRoute
  DemoBetterAuthRoute: typeof DemoBetterAuthRoute
  DemoTableRoute: typeof DemoTableRoute
  DemoTanstackQueryRoute: typeof DemoTanstackQueryRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  DemoFormAddressRoute: typeof DemoFormAddressRoute
  DemoFormSimpleRoute: typeof DemoFormSimpleRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/demo/tanstack-query': {
      id: '/demo/tanstack-query'
      path: '/demo/tanstack-query'
      fullPath: '/demo/tanstack-query'
      preLoaderRoute: typeof DemoTanstackQueryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/table': {
      id: '/demo/table'
      path: '/demo/table'
      fullPath: '/demo/table'
      preLoaderRoute: typeof DemoTableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/better-auth': {
      id: '/demo/better-auth'
      path: '/demo/better-auth'
      fullPath: '/demo/better-auth'
      preLoaderRoute: typeof DemoBetterAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/setup': {
      id: '/api/setup'
      path: '/api/setup'
      fullPath: '/api/setup'
      preLoaderRoute: typeof ApiSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/seed-data': {
      id: '/api/seed-data'
      path: '/api/seed-data'
      fullPath: '/api/seed-data'
      preLoaderRoute: typeof ApiSeedDataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/seed': {
      id: '/api/seed'
      path: '/api/seed'
      fullPath: '/api/seed'
      preLoaderRoute: typeof ApiSeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/yield-tracking': {
      id: '/_layout/yield-tracking'
      path: '/yield-tracking'
      fullPath: '/yield-tracking'
      preLoaderRoute: typeof LayoutYieldTrackingRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/settings': {
      id: '/_layout/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof LayoutSettingsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/print-requests': {
      id: '/_layout/print-requests'
      path: '/print-requests'
      fullPath: '/print-requests'
      preLoaderRoute: typeof LayoutPrintRequestsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/pos': {
      id: '/_layout/pos'
      path: '/pos'
      fullPath: '/pos'
      preLoaderRoute: typeof LayoutPosRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/pencatatan-manual': {
      id: '/_layout/pencatatan-manual'
      path: '/pencatatan-manual'
      fullPath: '/pencatatan-manual'
      preLoaderRoute: typeof LayoutPencatatanManualRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/order-history': {
      id: '/_layout/order-history'
      path: '/order-history'
      fullPath: '/order-history'
      preLoaderRoute: typeof LayoutOrderHistoryRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/data-penjualan': {
      id: '/_layout/data-penjualan'
      path: '/data-penjualan'
      fullPath: '/data-penjualan'
      preLoaderRoute: typeof LayoutDataPenjualanRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/dashboard': {
      id: '/_layout/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof LayoutDashboardRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/cancel-requests': {
      id: '/_layout/cancel-requests'
      path: '/cancel-requests'
      fullPath: '/cancel-requests'
      preLoaderRoute: typeof LayoutCancelRequestsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/audit-inventory': {
      id: '/_layout/audit-inventory'
      path: '/audit-inventory'
      fullPath: '/audit-inventory'
      preLoaderRoute: typeof LayoutAuditInventoryRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/waste/': {
      id: '/_layout/waste/'
      path: '/waste'
      fullPath: '/waste/'
      preLoaderRoute: typeof LayoutWasteIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/supplier-deliveries/': {
      id: '/_layout/supplier-deliveries/'
      path: '/supplier-deliveries'
      fullPath: '/supplier-deliveries/'
      preLoaderRoute: typeof LayoutSupplierDeliveriesIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/stock-transfers/': {
      id: '/_layout/stock-transfers/'
      path: '/stock-transfers'
      fullPath: '/stock-transfers/'
      preLoaderRoute: typeof LayoutStockTransfersIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/stock-opname/': {
      id: '/_layout/stock-opname/'
      path: '/stock-opname'
      fullPath: '/stock-opname/'
      preLoaderRoute: typeof LayoutStockOpnameIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/scm-transfers/': {
      id: '/_layout/scm-transfers/'
      path: '/scm-transfers'
      fullPath: '/scm-transfers/'
      preLoaderRoute: typeof LayoutScmTransfersIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/scm-procurements/': {
      id: '/_layout/scm-procurements/'
      path: '/scm-procurements'
      fullPath: '/scm-procurements/'
      preLoaderRoute: typeof LayoutScmProcurementsIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/scm-invoices/': {
      id: '/_layout/scm-invoices/'
      path: '/scm-invoices'
      fullPath: '/scm-invoices/'
      preLoaderRoute: typeof LayoutScmInvoicesIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/recipes/': {
      id: '/_layout/recipes/'
      path: '/recipes'
      fullPath: '/recipes/'
      preLoaderRoute: typeof LayoutRecipesIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/purchase-requisitions/': {
      id: '/_layout/purchase-requisitions/'
      path: '/purchase-requisitions'
      fullPath: '/purchase-requisitions/'
      preLoaderRoute: typeof LayoutPurchaseRequisitionsIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/purchase-orders/': {
      id: '/_layout/purchase-orders/'
      path: '/purchase-orders'
      fullPath: '/purchase-orders/'
      preLoaderRoute: typeof LayoutPurchaseOrdersIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/period-control/': {
      id: '/_layout/period-control/'
      path: '/period-control'
      fullPath: '/period-control/'
      preLoaderRoute: typeof LayoutPeriodControlIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/modifier-groups/': {
      id: '/_layout/modifier-groups/'
      path: '/modifier-groups'
      fullPath: '/modifier-groups/'
      preLoaderRoute: typeof LayoutModifierGroupsIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/inventory/': {
      id: '/_layout/inventory/'
      path: '/inventory'
      fullPath: '/inventory/'
      preLoaderRoute: typeof LayoutInventoryIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/ingredients/': {
      id: '/_layout/ingredients/'
      path: '/ingredients'
      fullPath: '/ingredients/'
      preLoaderRoute: typeof LayoutIngredientsIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/finance/': {
      id: '/_layout/finance/'
      path: '/finance'
      fullPath: '/finance/'
      preLoaderRoute: typeof LayoutFinanceIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/docs/': {
      id: '/_layout/docs/'
      path: '/docs'
      fullPath: '/docs/'
      preLoaderRoute: typeof LayoutDocsIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/delivery-notes/': {
      id: '/_layout/delivery-notes/'
      path: '/delivery-notes'
      fullPath: '/delivery-notes/'
      preLoaderRoute: typeof LayoutDeliveryNotesIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/categories/': {
      id: '/_layout/categories/'
      path: '/categories'
      fullPath: '/categories/'
      preLoaderRoute: typeof LayoutCategoriesIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/analytics/': {
      id: '/_layout/analytics/'
      path: '/analytics'
      fullPath: '/analytics/'
      preLoaderRoute: typeof LayoutAnalyticsIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/admin/': {
      id: '/_layout/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof LayoutAdminIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/demo/form/simple': {
      id: '/demo/form/simple'
      path: '/demo/form/simple'
      fullPath: '/demo/form/simple'
      preLoaderRoute: typeof DemoFormSimpleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/form/address': {
      id: '/demo/form/address'
      path: '/demo/form/address'
      fullPath: '/demo/form/address'
      preLoaderRoute: typeof DemoFormAddressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/stock-transfers/$trId': {
      id: '/_layout/stock-transfers/$trId'
      path: '/stock-transfers/$trId'
      fullPath: '/stock-transfers/$trId'
      preLoaderRoute: typeof LayoutStockTransfersTrIdRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/stock-opname/$soId': {
      id: '/_layout/stock-opname/$soId'
      path: '/stock-opname/$soId'
      fullPath: '/stock-opname/$soId'
      preLoaderRoute: typeof LayoutStockOpnameSoIdRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/scm-transfers/new': {
      id: '/_layout/scm-transfers/new'
      path: '/scm-transfers/new'
      fullPath: '/scm-transfers/new'
      preLoaderRoute: typeof LayoutScmTransfersNewRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/scm-transfers/$transferId': {
      id: '/_layout/scm-transfers/$transferId'
      path: '/scm-transfers/$transferId'
      fullPath: '/scm-transfers/$transferId'
      preLoaderRoute: typeof LayoutScmTransfersTransferIdRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/scm-procurements/new': {
      id: '/_layout/scm-procurements/new'
      path: '/scm-procurements/new'
      fullPath: '/scm-procurements/new'
      preLoaderRoute: typeof LayoutScmProcurementsNewRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/scm-procurements/$procurementId': {
      id: '/_layout/scm-procurements/$procurementId'
      path: '/scm-procurements/$procurementId'
      fullPath: '/scm-procurements/$procurementId'
      preLoaderRoute: typeof LayoutScmProcurementsProcurementIdRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/scm-invoices/$invId': {
      id: '/_layout/scm-invoices/$invId'
      path: '/scm-invoices/$invId'
      fullPath: '/scm-invoices/$invId'
      preLoaderRoute: typeof LayoutScmInvoicesInvIdRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/recipes/$recipeId': {
      id: '/_layout/recipes/$recipeId'
      path: '/recipes/$recipeId'
      fullPath: '/recipes/$recipeId'
      preLoaderRoute: typeof LayoutRecipesRecipeIdRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/purchase-requisitions/$prId': {
      id: '/_layout/purchase-requisitions/$prId'
      path: '/purchase-requisitions/$prId'
      fullPath: '/purchase-requisitions/$prId'
      preLoaderRoute: typeof LayoutPurchaseRequisitionsPrIdRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/purchase-orders/$poId': {
      id: '/_layout/purchase-orders/$poId'
      path: '/purchase-orders/$poId'
      fullPath: '/purchase-orders/$poId'
      preLoaderRoute: typeof LayoutPurchaseOrdersPoIdRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/period-control/$periodId': {
      id: '/_layout/period-control/$periodId'
      path: '/period-control/$periodId'
      fullPath: '/period-control/$periodId'
      preLoaderRoute: typeof LayoutPeriodControlPeriodIdRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/modifier-groups/$mgId': {
      id: '/_layout/modifier-groups/$mgId'
      path: '/modifier-groups/$mgId'
      fullPath: '/modifier-groups/$mgId'
      preLoaderRoute: typeof LayoutModifierGroupsMgIdRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/inventory/ledger': {
      id: '/_layout/inventory/ledger'
      path: '/inventory/ledger'
      fullPath: '/inventory/ledger'
      preLoaderRoute: typeof LayoutInventoryLedgerRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/ingredients/$ingId': {
      id: '/_layout/ingredients/$ingId'
      path: '/ingredients/$ingId'
      fullPath: '/ingredients/$ingId'
      preLoaderRoute: typeof LayoutIngredientsIngIdRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/finance/reconciliation': {
      id: '/_layout/finance/reconciliation'
      path: '/finance/reconciliation'
      fullPath: '/finance/reconciliation'
      preLoaderRoute: typeof LayoutFinanceReconciliationRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/finance/broken-stock': {
      id: '/_layout/finance/broken-stock'
      path: '/finance/broken-stock'
      fullPath: '/finance/broken-stock'
      preLoaderRoute: typeof LayoutFinanceBrokenStockRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/docs/stok-opname': {
      id: '/_layout/docs/stok-opname'
      path: '/docs/stok-opname'
      fullPath: '/docs/stok-opname'
      preLoaderRoute: typeof LayoutDocsStokOpnameRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/docs/resep-dan-pos': {
      id: '/_layout/docs/resep-dan-pos'
      path: '/docs/resep-dan-pos'
      fullPath: '/docs/resep-dan-pos'
      preLoaderRoute: typeof LayoutDocsResepDanPosRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/docs/produksi-internal': {
      id: '/_layout/docs/produksi-internal'
      path: '/docs/produksi-internal'
      fullPath: '/docs/produksi-internal'
      preLoaderRoute: typeof LayoutDocsProduksiInternalRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/docs/pengadaan': {
      id: '/_layout/docs/pengadaan'
      path: '/docs/pengadaan'
      fullPath: '/docs/pengadaan'
      preLoaderRoute: typeof LayoutDocsPengadaanRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/docs/mutasi-stok': {
      id: '/_layout/docs/mutasi-stok'
      path: '/docs/mutasi-stok'
      fullPath: '/docs/mutasi-stok'
      preLoaderRoute: typeof LayoutDocsMutasiStokRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/docs/kartu-stok': {
      id: '/_layout/docs/kartu-stok'
      path: '/docs/kartu-stok'
      fullPath: '/docs/kartu-stok'
      preLoaderRoute: typeof LayoutDocsKartuStokRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/docs/barang-masuk': {
      id: '/_layout/docs/barang-masuk'
      path: '/docs/barang-masuk'
      fullPath: '/docs/barang-masuk'
      preLoaderRoute: typeof LayoutDocsBarangMasukRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/delivery-notes/$dnId': {
      id: '/_layout/delivery-notes/$dnId'
      path: '/delivery-notes/$dnId'
      fullPath: '/delivery-notes/$dnId'
      preLoaderRoute: typeof LayoutDeliveryNotesDnIdRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/categories/$categoryId': {
      id: '/_layout/categories/$categoryId'
      path: '/categories/$categoryId'
      fullPath: '/categories/$categoryId'
      preLoaderRoute: typeof LayoutCategoriesCategoryIdRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/analytics/sales': {
      id: '/_layout/analytics/sales'
      path: '/analytics/sales'
      fullPath: '/analytics/sales'
      preLoaderRoute: typeof LayoutAnalyticsSalesRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/analytics/inventory': {
      id: '/_layout/analytics/inventory'
      path: '/analytics/inventory'
      fullPath: '/analytics/inventory'
      preLoaderRoute: typeof LayoutAnalyticsInventoryRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/admin/vouchers': {
      id: '/_layout/admin/vouchers'
      path: '/admin/vouchers'
      fullPath: '/admin/vouchers'
      preLoaderRoute: typeof LayoutAdminVouchersRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/admin/users': {
      id: '/_layout/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof LayoutAdminUsersRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/admin/system-logs': {
      id: '/_layout/admin/system-logs'
      path: '/admin/system-logs'
      fullPath: '/admin/system-logs'
      preLoaderRoute: typeof LayoutAdminSystemLogsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/admin/sales': {
      id: '/_layout/admin/sales'
      path: '/admin/sales'
      fullPath: '/admin/sales'
      preLoaderRoute: typeof LayoutAdminSalesRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/admin/platform-fees': {
      id: '/_layout/admin/platform-fees'
      path: '/admin/platform-fees'
      fullPath: '/admin/platform-fees'
      preLoaderRoute: typeof LayoutAdminPlatformFeesRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/admin/brands': {
      id: '/_layout/admin/brands'
      path: '/admin/brands'
      fullPath: '/admin/brands'
      preLoaderRoute: typeof LayoutAdminBrandsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/admin/branches': {
      id: '/_layout/admin/branches'
      path: '/admin/branches'
      fullPath: '/admin/branches'
      preLoaderRoute: typeof LayoutAdminBranchesRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/admin/audit-logs': {
      id: '/_layout/admin/audit-logs'
      path: '/admin/audit-logs'
      fullPath: '/admin/audit-logs'
      preLoaderRoute: typeof LayoutAdminAuditLogsRouteImport
      parentRoute: typeof LayoutRoute
    }
  }
}

interface LayoutRouteChildren {
  LayoutAuditInventoryRoute: typeof LayoutAuditInventoryRoute
  LayoutCancelRequestsRoute: typeof LayoutCancelRequestsRoute
  LayoutDashboardRoute: typeof LayoutDashboardRoute
  LayoutDataPenjualanRoute: typeof LayoutDataPenjualanRoute
  LayoutOrderHistoryRoute: typeof LayoutOrderHistoryRoute
  LayoutPencatatanManualRoute: typeof LayoutPencatatanManualRoute
  LayoutPosRoute: typeof LayoutPosRoute
  LayoutPrintRequestsRoute: typeof LayoutPrintRequestsRoute
  LayoutSettingsRoute: typeof LayoutSettingsRoute
  LayoutYieldTrackingRoute: typeof LayoutYieldTrackingRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
  LayoutAdminAuditLogsRoute: typeof LayoutAdminAuditLogsRoute
  LayoutAdminBranchesRoute: typeof LayoutAdminBranchesRoute
  LayoutAdminBrandsRoute: typeof LayoutAdminBrandsRoute
  LayoutAdminPlatformFeesRoute: typeof LayoutAdminPlatformFeesRoute
  LayoutAdminSalesRoute: typeof LayoutAdminSalesRoute
  LayoutAdminSystemLogsRoute: typeof LayoutAdminSystemLogsRoute
  LayoutAdminUsersRoute: typeof LayoutAdminUsersRoute
  LayoutAdminVouchersRoute: typeof LayoutAdminVouchersRoute
  LayoutAnalyticsInventoryRoute: typeof LayoutAnalyticsInventoryRoute
  LayoutAnalyticsSalesRoute: typeof LayoutAnalyticsSalesRoute
  LayoutCategoriesCategoryIdRoute: typeof LayoutCategoriesCategoryIdRoute
  LayoutDeliveryNotesDnIdRoute: typeof LayoutDeliveryNotesDnIdRoute
  LayoutDocsBarangMasukRoute: typeof LayoutDocsBarangMasukRoute
  LayoutDocsKartuStokRoute: typeof LayoutDocsKartuStokRoute
  LayoutDocsMutasiStokRoute: typeof LayoutDocsMutasiStokRoute
  LayoutDocsPengadaanRoute: typeof LayoutDocsPengadaanRoute
  LayoutDocsProduksiInternalRoute: typeof LayoutDocsProduksiInternalRoute
  LayoutDocsResepDanPosRoute: typeof LayoutDocsResepDanPosRoute
  LayoutDocsStokOpnameRoute: typeof LayoutDocsStokOpnameRoute
  LayoutFinanceBrokenStockRoute: typeof LayoutFinanceBrokenStockRoute
  LayoutFinanceReconciliationRoute: typeof LayoutFinanceReconciliationRoute
  LayoutIngredientsIngIdRoute: typeof LayoutIngredientsIngIdRoute
  LayoutInventoryLedgerRoute: typeof LayoutInventoryLedgerRoute
  LayoutModifierGroupsMgIdRoute: typeof LayoutModifierGroupsMgIdRoute
  LayoutPeriodControlPeriodIdRoute: typeof LayoutPeriodControlPeriodIdRoute
  LayoutPurchaseOrdersPoIdRoute: typeof LayoutPurchaseOrdersPoIdRoute
  LayoutPurchaseRequisitionsPrIdRoute: typeof LayoutPurchaseRequisitionsPrIdRoute
  LayoutRecipesRecipeIdRoute: typeof LayoutRecipesRecipeIdRoute
  LayoutScmInvoicesInvIdRoute: typeof LayoutScmInvoicesInvIdRoute
  LayoutScmProcurementsProcurementIdRoute: typeof LayoutScmProcurementsProcurementIdRoute
  LayoutScmProcurementsNewRoute: typeof LayoutScmProcurementsNewRoute
  LayoutScmTransfersTransferIdRoute: typeof LayoutScmTransfersTransferIdRoute
  LayoutScmTransfersNewRoute: typeof LayoutScmTransfersNewRoute
  LayoutStockOpnameSoIdRoute: typeof LayoutStockOpnameSoIdRoute
  LayoutStockTransfersTrIdRoute: typeof LayoutStockTransfersTrIdRoute
  LayoutAdminIndexRoute: typeof LayoutAdminIndexRoute
  LayoutAnalyticsIndexRoute: typeof LayoutAnalyticsIndexRoute
  LayoutCategoriesIndexRoute: typeof LayoutCategoriesIndexRoute
  LayoutDeliveryNotesIndexRoute: typeof LayoutDeliveryNotesIndexRoute
  LayoutDocsIndexRoute: typeof LayoutDocsIndexRoute
  LayoutFinanceIndexRoute: typeof LayoutFinanceIndexRoute
  LayoutIngredientsIndexRoute: typeof LayoutIngredientsIndexRoute
  LayoutInventoryIndexRoute: typeof LayoutInventoryIndexRoute
  LayoutModifierGroupsIndexRoute: typeof LayoutModifierGroupsIndexRoute
  LayoutPeriodControlIndexRoute: typeof LayoutPeriodControlIndexRoute
  LayoutPurchaseOrdersIndexRoute: typeof LayoutPurchaseOrdersIndexRoute
  LayoutPurchaseRequisitionsIndexRoute: typeof LayoutPurchaseRequisitionsIndexRoute
  LayoutRecipesIndexRoute: typeof LayoutRecipesIndexRoute
  LayoutScmInvoicesIndexRoute: typeof LayoutScmInvoicesIndexRoute
  LayoutScmProcurementsIndexRoute: typeof LayoutScmProcurementsIndexRoute
  LayoutScmTransfersIndexRoute: typeof LayoutScmTransfersIndexRoute
  LayoutStockOpnameIndexRoute: typeof LayoutStockOpnameIndexRoute
  LayoutStockTransfersIndexRoute: typeof LayoutStockTransfersIndexRoute
  LayoutSupplierDeliveriesIndexRoute: typeof LayoutSupplierDeliveriesIndexRoute
  LayoutWasteIndexRoute: typeof LayoutWasteIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutAuditInventoryRoute: LayoutAuditInventoryRoute,
  LayoutCancelRequestsRoute: LayoutCancelRequestsRoute,
  LayoutDashboardRoute: LayoutDashboardRoute,
  LayoutDataPenjualanRoute: LayoutDataPenjualanRoute,
  LayoutOrderHistoryRoute: LayoutOrderHistoryRoute,
  LayoutPencatatanManualRoute: LayoutPencatatanManualRoute,
  LayoutPosRoute: LayoutPosRoute,
  LayoutPrintRequestsRoute: LayoutPrintRequestsRoute,
  LayoutSettingsRoute: LayoutSettingsRoute,
  LayoutYieldTrackingRoute: LayoutYieldTrackingRoute,
  LayoutIndexRoute: LayoutIndexRoute,
  LayoutAdminAuditLogsRoute: LayoutAdminAuditLogsRoute,
  LayoutAdminBranchesRoute: LayoutAdminBranchesRoute,
  LayoutAdminBrandsRoute: LayoutAdminBrandsRoute,
  LayoutAdminPlatformFeesRoute: LayoutAdminPlatformFeesRoute,
  LayoutAdminSalesRoute: LayoutAdminSalesRoute,
  LayoutAdminSystemLogsRoute: LayoutAdminSystemLogsRoute,
  LayoutAdminUsersRoute: LayoutAdminUsersRoute,
  LayoutAdminVouchersRoute: LayoutAdminVouchersRoute,
  LayoutAnalyticsInventoryRoute: LayoutAnalyticsInventoryRoute,
  LayoutAnalyticsSalesRoute: LayoutAnalyticsSalesRoute,
  LayoutCategoriesCategoryIdRoute: LayoutCategoriesCategoryIdRoute,
  LayoutDeliveryNotesDnIdRoute: LayoutDeliveryNotesDnIdRoute,
  LayoutDocsBarangMasukRoute: LayoutDocsBarangMasukRoute,
  LayoutDocsKartuStokRoute: LayoutDocsKartuStokRoute,
  LayoutDocsMutasiStokRoute: LayoutDocsMutasiStokRoute,
  LayoutDocsPengadaanRoute: LayoutDocsPengadaanRoute,
  LayoutDocsProduksiInternalRoute: LayoutDocsProduksiInternalRoute,
  LayoutDocsResepDanPosRoute: LayoutDocsResepDanPosRoute,
  LayoutDocsStokOpnameRoute: LayoutDocsStokOpnameRoute,
  LayoutFinanceBrokenStockRoute: LayoutFinanceBrokenStockRoute,
  LayoutFinanceReconciliationRoute: LayoutFinanceReconciliationRoute,
  LayoutIngredientsIngIdRoute: LayoutIngredientsIngIdRoute,
  LayoutInventoryLedgerRoute: LayoutInventoryLedgerRoute,
  LayoutModifierGroupsMgIdRoute: LayoutModifierGroupsMgIdRoute,
  LayoutPeriodControlPeriodIdRoute: LayoutPeriodControlPeriodIdRoute,
  LayoutPurchaseOrdersPoIdRoute: LayoutPurchaseOrdersPoIdRoute,
  LayoutPurchaseRequisitionsPrIdRoute: LayoutPurchaseRequisitionsPrIdRoute,
  LayoutRecipesRecipeIdRoute: LayoutRecipesRecipeIdRoute,
  LayoutScmInvoicesInvIdRoute: LayoutScmInvoicesInvIdRoute,
  LayoutScmProcurementsProcurementIdRoute:
    LayoutScmProcurementsProcurementIdRoute,
  LayoutScmProcurementsNewRoute: LayoutScmProcurementsNewRoute,
  LayoutScmTransfersTransferIdRoute: LayoutScmTransfersTransferIdRoute,
  LayoutScmTransfersNewRoute: LayoutScmTransfersNewRoute,
  LayoutStockOpnameSoIdRoute: LayoutStockOpnameSoIdRoute,
  LayoutStockTransfersTrIdRoute: LayoutStockTransfersTrIdRoute,
  LayoutAdminIndexRoute: LayoutAdminIndexRoute,
  LayoutAnalyticsIndexRoute: LayoutAnalyticsIndexRoute,
  LayoutCategoriesIndexRoute: LayoutCategoriesIndexRoute,
  LayoutDeliveryNotesIndexRoute: LayoutDeliveryNotesIndexRoute,
  LayoutDocsIndexRoute: LayoutDocsIndexRoute,
  LayoutFinanceIndexRoute: LayoutFinanceIndexRoute,
  LayoutIngredientsIndexRoute: LayoutIngredientsIndexRoute,
  LayoutInventoryIndexRoute: LayoutInventoryIndexRoute,
  LayoutModifierGroupsIndexRoute: LayoutModifierGroupsIndexRoute,
  LayoutPeriodControlIndexRoute: LayoutPeriodControlIndexRoute,
  LayoutPurchaseOrdersIndexRoute: LayoutPurchaseOrdersIndexRoute,
  LayoutPurchaseRequisitionsIndexRoute: LayoutPurchaseRequisitionsIndexRoute,
  LayoutRecipesIndexRoute: LayoutRecipesIndexRoute,
  LayoutScmInvoicesIndexRoute: LayoutScmInvoicesIndexRoute,
  LayoutScmProcurementsIndexRoute: LayoutScmProcurementsIndexRoute,
  LayoutScmTransfersIndexRoute: LayoutScmTransfersIndexRoute,
  LayoutStockOpnameIndexRoute: LayoutStockOpnameIndexRoute,
  LayoutStockTransfersIndexRoute: LayoutStockTransfersIndexRoute,
  LayoutSupplierDeliveriesIndexRoute: LayoutSupplierDeliveriesIndexRoute,
  LayoutWasteIndexRoute: LayoutWasteIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  AboutRoute: AboutRoute,
  LoginRoute: LoginRoute,
  ApiSeedRoute: ApiSeedRoute,
  ApiSeedDataRoute: ApiSeedDataRoute,
  ApiSetupRoute: ApiSetupRoute,
  DemoBetterAuthRoute: DemoBetterAuthRoute,
  DemoTableRoute: DemoTableRoute,
  DemoTanstackQueryRoute: DemoTanstackQueryRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  DemoFormAddressRoute: DemoFormAddressRoute,
  DemoFormSimpleRoute: DemoFormSimpleRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
